dotnet-project-file-analyzers/dotnet-project-file-analyzers

specs/DotNetProjectFile.Analyzers.Specs/Design_specs.cs
specs/DotNetProjectFile.Analyzers.Specs/Rules/All.cs
src/DotNetProjectFile.Analyzers/DotNetProjectFile.Analyzers.csproj
src/DotNetProjectFile.Analyzers/MsBuild/Projects.cs

The own project file can not be validated by linking itself. By calling a unit test, this can be solved.

Validate own project file

---

dotnet-project-file-analyzers.sln
props/common.props
specs/DotNetProjectFile.Analyzers.Specs/DotNetProjectFile.Analyzers.Specs.csproj
src/DotNetProjectFile.Analyzers/Analyzers/MsBuild/RunNuGetSecurityAuditsAutomatically.cs
src/DotNetProjectFile.Analyzers/Analyzers/MsBuild/UseAnalyzers.cs
src/DotNetProjectFile.Analyzers/Analyzers/MsBuild/UseAnalyzersForPackages.cs
src/DotNetProjectFile.Analyzers/Analyzers/MsBuild/UseSonarAnalyzers.cs
src/DotNetProjectFile.Analyzers/DotNetProjectFile.Analyzers.csproj

It should only report on projects, but should check for imported props.

FP Proj1003: SonarAnalyzers defined in props are not regonized

---

dotnet-project-file-analyzers.sln
specs/Benchmarks/Benchmarks.csproj
specs/Benchmarks/Program.cs
specs/Benchmarks/Properties/GlobalUsings.cs
specs/Benchmarks/README.md
specs/Benchmarks/RunAll.cs

To monitor durations.
|        File |        Mean |     Error |      StdDev |
|------------ |------------:|----------:|------------:|
| CompliantCS |    631.4 us |   8.75 us |     8.18 us |
| CompliantVB |  1,575.4 us |  30.68 us |    39.89 us |
|     Project | 22,200.3 us | 441.18 us | 1,279.93 us |

Adding benchmarks

---

projects/CompliantVBPackage/CompliantVBPackage.vbproj
specs/DotNetProjectFile.Analyzers.Specs/Rules/MS_Build/Add_additional_files.cs
specs/DotNetProjectFile.Analyzers.Specs/Rules/MS_Build/Avoid_license_url.cs
specs/DotNetProjectFile.Analyzers.Specs/Rules/MS_Build/Define_is_packable.cs
specs/DotNetProjectFile.Analyzers.Specs/Rules/MS_Build/Define_output_type.cs
specs/DotNetProjectFile.Analyzers.Specs/Rules/MS_Build/Define_package_info.cs
specs/DotNetProjectFile.Analyzers.Specs/Rules/MS_Build/Define_package_reference_assets_as_attributes.cs
specs/DotNetProjectFile.Analyzers.Specs/Rules/MS_Build/Define_properties_once.cs
specs/DotNetProjectFile.Analyzers.Specs/Rules/MS_Build/Define_single_target_framework.cs
specs/DotNetProjectFile.Analyzers.Specs/Rules/MS_Build/Define_usings_explicit.cs
specs/DotNetProjectFile.Analyzers.Specs/Rules/MS_Build/Project_file_could_not_be_located.cs
specs/DotNetProjectFile.Analyzers.Specs/Rules/MS_Build/Remove_empty_nodes.cs
specs/DotNetProjectFile.Analyzers.Specs/Rules/MS_Build/Remove_folder_nodes.cs
specs/DotNetProjectFile.Analyzers.Specs/Rules/MS_Build/Run_NuGet_security_audits_automatically.cs
specs/DotNetProjectFile.Analyzers.Specs/Rules/MS_Build/Update_legacy_project.cs
specs/DotNetProjectFile.Analyzers.Specs/Rules/MS_Build/Use_analyzers_for_packages.cs
specs/DotNetProjectFile.Analyzers.Specs/Rules/MS_Build/Use_dotnet_project_file_analyzers.cs
specs/DotNetProjectFile.Analyzers.Specs/Rules/RESX/Add_invariant_fallback_resources.cs
specs/DotNetProjectFile.Analyzers.Specs/Rules/RESX/Add_invariant_fallback_values.cs
specs/DotNetProjectFile.Analyzers.Specs/Rules/RESX/Define_data_in_resource.cs
specs/DotNetProjectFile.Analyzers.Specs/Rules/RESX/Embed_valid_resource_files.cs
specs/DotNetProjectFile.Analyzers.Specs/Rules/RESX/Sort_data_alphabetically.cs

If the consequence is that VB.NET projects have no part in it, so be it.

Ensure build runs

---

specs/DotNetProjectFile.Analyzers.Specs/IO/File_path_compare.cs
src/DotNetProjectFile.Analyzers/Analyzers/MsBuild/OrderPackageReferencesAlphabetically.cs
src/DotNetProjectFile.Analyzers/Analyzers/MsBuild/OrderProjectReferencesAlphabetically.cs
src/DotNetProjectFile.Analyzers/DotNetProjectFile.Analyzers.csproj
src/DotNetProjectFile.Analyzers/IO/FilePathComparer.cs
src/DotNetProjectFile.Analyzers/IO/FileSystem.cs
src/DotNetProjectFile.Analyzers/MsBuild/PackageReference.cs

Sort file paths properly

---

src/DotNetProjectFile.Analyzers/DotNetProjectFile.Analyzers.csproj

Use more used `PolySharp` instead of `BackwardsCompatibleFeatures`.

Use PolySharp

---

src/DotNetProjectFile.Analyzers/DotNetProjectFile.Analyzers.csproj

Mark analyzer as dev dependency

---

src/DotNetProjectFile.Analyzers/Diagnostics/MissingAnalyzerConfigOptions.cs
src/DotNetProjectFile.Analyzers/Diagnostics/ProjectFileAnalysisContext.cs
src/DotNetProjectFile.Analyzers/MsBuild/Project.cs

Expose analyzer configuration

---

dotnet-project-file-analyzers.sln
projects/CompliantCSharpPackage/CompliantCSharpPackage.csproj
projects/GeneratePackageNotPackable/GeneratePackageNotPackable.csproj
projects/GeneratePackageNotPackable/Placeholder.cs
specs/DotNetProjectFile.Analyzers.Specs/Rules/MS_Build/Avoid_generate_on_build.cs
src/DotNetProjectFile.Analyzers/Analyzers/MsBuild/AvoidGeneratePackageOnBuildWhenNotPackable.cs
src/DotNetProjectFile.Analyzers/DotNetProjectFile.Analyzers.csproj
src/DotNetProjectFile.Analyzers/MsBuild/GeneratePackageOnBuild.cs
src/DotNetProjectFile.Analyzers/MsBuild/PropertyGroup.cs
src/DotNetProjectFile.Analyzers/README.md
src/DotNetProjectFile.Analyzers/Rule.cs

Closes #66 
Documentation PR: https://github.com/dotnet-project-file-analyzers/dotnet-project-file-analyzers.github.io/pull/7

Proj0600 Avoid generate package on build when project is not packable

---

README.md

Add documentation on changing rule severity

---

dotnet-project-file-analyzers.sln
projects/CompliantCSharpPackage/CompliantCSharpPackage.csproj
projects/NoBaselineVersion/NoBaselineVersion.csproj
projects/NoBaselineVersion/Placeholder.cs
projects/PackageValidationDisabled/PackageValidationDisabled.csproj
projects/PackageValidationDisabled/Placeholder.cs
specs/DotNetProjectFile.Analyzers.Specs/Rules/MS_Build/Define_package_validation_baseline_version.cs
specs/DotNetProjectFile.Analyzers.Specs/Rules/MS_Build/Enable_package_validation.cs
src/DotNetProjectFile.Analyzers/Analyzers/MsBuild/DefinePackageInfo.cs
src/DotNetProjectFile.Analyzers/Analyzers/MsBuild/DefinePackageValidationBaselineVersion.cs
src/DotNetProjectFile.Analyzers/Analyzers/MsBuild/EnablePackageValidation.cs
src/DotNetProjectFile.Analyzers/DotNetProjectFile.Analyzers.csproj
src/DotNetProjectFile.Analyzers/Extensions/DotNetProjectFile.MsBuild.Project.cs
src/DotNetProjectFile.Analyzers/MsBuild/DevelopmentDependency.cs
src/DotNetProjectFile.Analyzers/MsBuild/EnablePackageValidation.cs
src/DotNetProjectFile.Analyzers/MsBuild/MsBuildDefaults.cs
src/DotNetProjectFile.Analyzers/MsBuild/PackageValidationBaselineVersion.cs
src/DotNetProjectFile.Analyzers/MsBuild/PropertyGroup.cs
src/DotNetProjectFile.Analyzers/Rule.cs

Closes #24 
Documentation: https://github.com/dotnet-project-file-analyzers/dotnet-project-file-analyzers.github.io/pull/8

New Rules: Enable package validation (Proj0240 & Proj0241)

---

dotnet-project-file-analyzers.sln
projects/BackwardSlashes/BackwardSlashes.csproj
projects/FolderNodes/FolderNodes.csproj
projects/PackagesWithAnalyzers/PackagesWithAnalyzers.csproj
projects/props/simple.props
specs/DotNetProjectFile.Analyzers.Specs/Rules/MS_Build/Use_forward_slashes_in_paths.cs
src/DotNetProjectFile.Analyzers/Analyzers/MsBuild/UseForwardSlashesInPaths.cs
src/DotNetProjectFile.Analyzers/DotNetProjectFile.Analyzers.csproj
src/DotNetProjectFile.Analyzers/MsBuild/Node.cs
src/DotNetProjectFile.Analyzers/MsBuild/NodeFactory.cs
src/DotNetProjectFile.Analyzers/MsBuild/Nodes.T.cs
src/DotNetProjectFile.Analyzers/MsBuild/Project.cs
src/DotNetProjectFile.Analyzers/README.md
src/DotNetProjectFile.Analyzers/Rule.cs

New Rule 0023: Use forward slashes

---

dotnet-project-file-analyzers.sln
projects/NonAlphabeticalPackageVersions/NonAlphabeticalPackageVersions.csproj
specs/DotNetProjectFile.Analyzers.Specs/Rules/MS_Build/Order_package_versions_in_alphabetical_order.cs
src/DotNetProjectFile.Analyzers/Analyzers/MsBuild/AvoidUsingMoq.cs
src/DotNetProjectFile.Analyzers/Analyzers/MsBuild/OrderPackageVersionsAlphabetically.cs
src/DotNetProjectFile.Analyzers/DotNetProjectFile.Analyzers.csproj
src/DotNetProjectFile.Analyzers/MsBuild/ItemGroup.cs
src/DotNetProjectFile.Analyzers/MsBuild/PackageReference.cs
src/DotNetProjectFile.Analyzers/MsBuild/PackageVersion.cs
src/DotNetProjectFile.Analyzers/README.md
src/DotNetProjectFile.Analyzers/Rule.cs

Resolves #126 
Documentation: https://github.com/dotnet-project-file-analyzers/dotnet-project-file-analyzers.github.io/pull/15

Proj0024: Order package versions alphabetically

---

projects/UnstableVersionsCPM/Directory.Packages.props
projects/UnstableVersionsCPM/UnstableVersionsCPM.csproj
specs/DotNetProjectFile.Analyzers.Specs/Rules/MS_Build/Package_references_should_be_stable.cs
src/DotNetProjectFile.Analyzers/Analyzers/MsBuild/PackageReferencesShouldBeStable.cs
src/DotNetProjectFile.Analyzers/DotNetProjectFile.Analyzers.csproj
src/DotNetProjectFile.Analyzers/Rule.cs

Report unstable versions defined via CPM

---

projects/EnableCPMLocally/Directory.Packages.props
projects/EnableCPMLocally/EnableCPMLocally.csproj
specs/DotNetProjectFile.Analyzers.Specs/Rules/MS_Build/Enable_CPM_globally.cs
src/DotNetProjectFile.Analyzers/Analyzers/MsBuild/EnableCentralPackageManagementCentrally.cs
src/DotNetProjectFile.Analyzers/DotNetProjectFile.Analyzers.csproj
src/DotNetProjectFile.Analyzers/README.md
src/DotNetProjectFile.Analyzers/Rule.cs

Enabling it per project would defy the purpose of CPM.

Proj0802: Enable Central Package Management centrally

---

projects/PackageReferenceWithoutVersion/PackageReferenceWithoutVersion.csproj
specs/DotNetProjectFile.Analyzers.Specs/Rules/MS_Build/Define_package_reference_version.cs
src/DotNetProjectFile.Analyzers/Analyzers/MsBuild/DefinePackageReferenceVersion.cs
src/DotNetProjectFile.Analyzers/DotNetProjectFile.Analyzers.csproj
src/DotNetProjectFile.Analyzers/README.md
src/DotNetProjectFile.Analyzers/Rule.cs

Define PackageReference version

---

projects/MisuseVersion/Directory.Packages.props
projects/MisuseVersion/MisuseVersion.csproj
specs/DotNetProjectFile.Analyzers.Specs/Rules/MS_Build/Use_VersionOverride_only_with_CPM.cs
specs/DotNetProjectFile.Analyzers.Specs/Rules/MS_Build/Use_Version_only_without_CPM.cs
src/DotNetProjectFile.Analyzers/Analyzers/MsBuild/UseVersionOnlyWithoutCpm.cs
src/DotNetProjectFile.Analyzers/DotNetProjectFile.Analyzers.csproj
src/DotNetProjectFile.Analyzers/README.md
src/DotNetProjectFile.Analyzers/Rule.cs

Basically the opposite of #151

Proj0804: Only use Version when CPM is not enabled]

---

projects/VersionUpdateNotDifferent/Directory.Packages.props
projects/VersionUpdateNotDifferent/VersionUpdateNotDifferent.csproj
specs/DotNetProjectFile.Analyzers.Specs/Rules/MS_Build/VersionOverride_should_change_version.cs
src/DotNetProjectFile.Analyzers/Analyzers/MsBuild/AddAdditionalFile.cs
src/DotNetProjectFile.Analyzers/Analyzers/MsBuild/VersionOverrideShouldChangeVersion.cs
src/DotNetProjectFile.Analyzers/DotNetProjectFile.Analyzers.csproj
src/DotNetProjectFile.Analyzers/README.md
src/DotNetProjectFile.Analyzers/Rule.cs

Otherwise it would make no sense.

Proj0806: VersionOverride should change the version

---

dictionary.dic
projects/MissingCDATA/MissingCDATA.csproj
specs/DotNetProjectFile.Analyzers.Specs/Rules/MS_Build/Use_CDATA_for_large_texts.cs
src/DotNetProjectFile.Analyzers/Analyzers/MsBuild/UseCDATAForLargeTexts.cs
src/DotNetProjectFile.Analyzers/DotNetProjectFile.Analyzers.csproj
src/DotNetProjectFile.Analyzers/Extensions/System.Xml.Linq.XContainer.cs
src/DotNetProjectFile.Analyzers/README.md
src/DotNetProjectFile.Analyzers/Rule.cs
src/DotNetProjectFile.Analyzers/Xml/XmlPositions.cs

Particularity useful for `<PageReleaseNotes>`  but might become relevant for others in the nearby future.

Proj1701: Use <![CDATA[ for large texts

---

dictionary.dic
projects/TargetFramework/TargetFramework.csproj
projects/TfmsMixed/TfmsMixed.csproj
projects/TfmsMixed/common.props
specs/DotNetProjectFile.Analyzers.Specs/Rules/MS_Build/Override_TargetFrameworks_with_TargetFrameworks.cs
specs/DotNetProjectFile.Analyzers.Specs/Rules/MS_Build/Update_TargetFrameworks_with_TargetFrameworks.cs
src/DotNetProjectFile.Analyzers/Analyzers/MsBuild/OverrideTargetFrameworksWithTargetFrameworks.cs
src/DotNetProjectFile.Analyzers/Analyzers/MsBuild/UpdateTargetFrameworksWithTargetFrameworks.cs
src/DotNetProjectFile.Analyzers/Analyzers/MsBuildProjectFileAnalyzer.cs
src/DotNetProjectFile.Analyzers/DotNetProjectFile.Analyzers.csproj
src/DotNetProjectFile.Analyzers/README.md
src/DotNetProjectFile.Analyzers/Rule.cs

Proj0027: Update <TargetFrameworks> with <TargetFrameworks>

---

projects/Conditional/Conditional.csproj
specs/DotNetProjectFile.Analyzers.Specs/Rules/MS_Build/Define_conditions_on_level_1.cs
src/DotNetProjectFile.Analyzers/Analyzers/MsBuild/DefineConditionsOnLevel1.cs
src/DotNetProjectFile.Analyzers/DotNetProjectFile.Analyzers.csproj
src/DotNetProjectFile.Analyzers/MsBuild/Otherwise.cs
src/DotNetProjectFile.Analyzers/README.md
src/DotNetProjectFile.Analyzers/Rule.cs

Proj0028: Define conditions on level 1

---

src/DotNetProjectFile.Analyzers/Analyzers/Generic/OnlyUseUTF8WithoutBom.cs
src/DotNetProjectFile.Analyzers/DotNetProjectFile.Analyzers.csproj

Proj3000: Don't crash on non-existing files

---

projects/FaultyIndenting/FaultyIndenting.resx
src/DotNetProjectFile.Analyzers/Analyzers/Helpers/IdentationChecker.cs
src/DotNetProjectFile.Analyzers/Analyzers/MsBuild/IndentXml.cs
src/DotNetProjectFile.Analyzers/Analyzers/Resx/IndentResx.cs
src/DotNetProjectFile.Analyzers/DotNetProjectFile.Analyzers.csproj

Fix FP on 2100

---

README.md
projects/CompliantCSharpPackage/CompliantCSharpPackage.csproj
projects/CompliantVBPackage/CompliantVBPackage.vbproj
projects/NoAuthors/NoAuthors.csproj
projects/NoCopyright/NoCopyright.csproj
projects/NoDescription/NoDescription.csproj
projects/NoIcon/NoIcon.csproj
projects/NoIconUrl/NoIconUrl.csproj
projects/NoLicense/NoLicense.csproj
projects/NoProductName/NoProductName.csproj
projects/NoReadme/NoReadme.csproj
projects/NoReleaseNotes/NoReleaseNotes.csproj
projects/NoRepositoryUrl/NoRepositoryUrl.csproj
projects/NoTags/NoTags.csproj
projects/NoUrl/NoUrl.csproj
projects/NoVersion/NoVersion.csproj
projects/WithLicenseFile/WithLicenseFile.csproj
projects/WithLicenseUrl/WithLicenseUrl.csproj
specs/DotNetProjectFile.Analyzers.Specs/Rules/MS_Build/NuGet packages/Avoid_license_url.cs
specs/DotNetProjectFile.Analyzers.Specs/Rules/MS_Build/NuGet packages/Define_package_info.cs
src/DotNetProjectFile.Analyzers/Analyzers/MsBuild/DefinePackageInfo.cs
src/DotNetProjectFile.Analyzers/DotNetProjectFile.Analyzers.csproj
src/DotNetProjectFile.Analyzers/MsBuild/ProductName.cs
src/DotNetProjectFile.Analyzers/README.md
src/DotNetProjectFile.Analyzers/Rule.cs

Check on `<ProductName>` was missing.

Proj0216: Define the product name explicitly

---

projects/WithDirectoryBuildProps/Directory.Build.targets
specs/DotNetProjectFile.Analyzers.Specs/MS_Build/Directory_Build_props_specs.cs
src/DotNetProjectFile.Analyzers/DotNetProjectFile.Analyzers.csproj
src/DotNetProjectFile.Analyzers/MsBuild/Project.cs

Support Directory.Build.targets

---

src/DotNetProjectFile.Analyzers/NuGet/Packages.cs

As was a list I was still working on that was included yet when #241 was merged.

Add packages to be included as private assets part 2

---

projects/CompliantCSharpPackage/CompliantCSharpPackage.csproj
projects/PackageWithSBOMDisabled/PackageWithSBOMDisabled.csproj
projects/PackageWithoutSBOM/PackageWithoutSBOM.csproj
projects/PackageWithoutSBOMReference/PackageWithoutSBOMReference.csproj
specs/DotNetProjectFile.Analyzers.Specs/Rules/MS_Build/Enable_package_validation.cs
specs/DotNetProjectFile.Analyzers.Specs/Rules/MS_Build/Generate_SBOM.cs
src/DotNetProjectFile.Analyzers.Sdk/DotNetProjectFile.Analyzers.Sdk.csproj
src/DotNetProjectFile.Analyzers/Analyzers/MsBuild/GenerateSbom.cs
src/DotNetProjectFile.Analyzers/Analyzers/MsBuild/TestProjectsRequireSdk.cs
src/DotNetProjectFile.Analyzers/DotNetProjectFile.Analyzers.csproj
src/DotNetProjectFile.Analyzers/MsBuild/GenerateSBOM.cs
src/DotNetProjectFile.Analyzers/MsBuild/PropertyGroup.cs
src/DotNetProjectFile.Analyzers/NuGet/BuildExtension.cs
src/DotNetProjectFile.Analyzers/NuGet/Packages.cs
src/DotNetProjectFile.Analyzers/README.md
src/DotNetProjectFile.Analyzers/Rule.cs

Proj0243: Generate SBOM

---

specs/DotNetProjectFile.Analyzers.Specs/Parsing/Examples/bug_00251.ini
specs/DotNetProjectFile.Analyzers.Specs/Parsing/INI_syntax.cs
specs/DotNetProjectFile.Analyzers.Specs/TestTools/Source.cs
src/DotNetProjectFile.Analyzers.Sdk/DotNetProjectFile.Analyzers.Sdk.csproj
src/DotNetProjectFile.Analyzers.Sdk/DotNetProjectFile.Analyzers.Sdk.props
src/DotNetProjectFile.Analyzers/DotNetProjectFile.Analyzers.csproj
src/DotNetProjectFile.Analyzers/Grammr/Text/InvalidPattern.cs
src/DotNetProjectFile.Analyzers/Grammr/Text/SourceSpan.cs
src/DotNetProjectFile.Analyzers/Grammr/Text/SourceSpanLogger.cs
src/DotNetProjectFile.Analyzers/Grammr/Text/SourceSpanToken.cs
src/DotNetProjectFile.Analyzers/IO/Globbing/GlobParser.cs
src/DotNetProjectFile.Analyzers/Ini/IniFileSyntax.cs
src/DotNetProjectFile.Analyzers/Parsing/ParseBuffer.cs
src/DotNetProjectFile.Analyzers/Parsing/Parser.cs
src/DotNetProjectFile.Analyzers/Syntax/SyntaxNode.cs
src/DotNetProjectFile.Analyzers/Syntax/SyntaxNodeResolver.cs
src/DotNetProjectFile.Analyzers/Syntax/SyntaxTree.cs
src/DotNetProjectFile.Analyzers/Syntax/Unparsable.cs

Fix crashing INI parsing

---

projects/BinaryFormattingEnabled/BinaryFormattingEnabled.csproj
specs/DotNetProjectFile.Analyzers.Specs/Rules/MS_Build/Migrate_away_from_BinaryFormatter.cs
src/DotNetProjectFile.Analyzers/Analyzers/MsBuild/MigrateAwayFromBinaryFormatter.cs
src/DotNetProjectFile.Analyzers/DotNetProjectFile.Analyzers.csproj
src/DotNetProjectFile.Analyzers/MsBuild/EnableUnsafeBinaryFormatterSerialization.cs
src/DotNetProjectFile.Analyzers/MsBuild/PropertyGroup.cs
src/DotNetProjectFile.Analyzers/README.md
src/DotNetProjectFile.Analyzers/Rule.cs

Proj0032: Migarate away from BinaryFormatter

---

projects/ToDo/ToDo.csproj
specs/DotNetProjectFile.Analyzers.Specs/Rules/MS_Build/Track_TODO_tags.cs
specs/DotNetProjectFile.Analyzers.Specs/Rules/ToDoChecker_specs.cs
specs/DotNetProjectFile.Analyzers.Specs/XML/XML_positions.cs
src/DotNetProjectFile.Analyzers/Analyzers/Helpers/ToDoChecker.cs
src/DotNetProjectFile.Analyzers/Analyzers/MsBuild/TrackToDoTags.cs
src/DotNetProjectFile.Analyzers/Diagnostics/Category.cs
src/DotNetProjectFile.Analyzers/DotNetProjectFile.Analyzers.csproj
src/DotNetProjectFile.Analyzers/README.md
src/DotNetProjectFile.Analyzers/Rule.cs
src/DotNetProjectFile.Analyzers/Xml/XmlComment.cs
src/DotNetProjectFile.Analyzers/Xml/XmlPositions.cs

Note that there will be a follow-up also implementing this for RESX files.
Closes #250

Proj0033: Track uses of ""TODO"" tags

---

props/common.props
specs/DotNetProjectFile.Analyzers.Specs/Collections/AppendOnlyCollection_specs.cs
src/DotNetProjectFile.Analyzers/Collections/AppendOnlyCollection.cs
src/DotNetProjectFile.Analyzers/Collections/Enumerator.cs
src/DotNetProjectFile.Analyzers/DotNetProjectFile.Analyzers.csproj

Generic version of [Qowaiv's internal AppendOnlyCollection](https://github.com/Qowaiv/qowaiv-domainmodel/blob/main/src/Qowaiv.DomainModel/Internal/AppendOnlyCollection.cs), used to be an append only event buffer.

Added AppendOnlyCollection to improve performance of parsing

---

src/DotNetProjectFile.Analyzers/DotNetProjectFile.Analyzers.csproj
src/DotNetProjectFile.Analyzers/MsBuild/Using.cs

Fix incorrect parsing of Using node's Static property

---

projects/CompliantCSharpPackage/CompliantCSharpPackage.csproj
projects/GenerateDocumentationFileDisabledWithFile/GenerateDocumentationFileDisabledWithFile.csproj
projects/GenerateDocumentationFileDisabledWithoutFile/GenerateDocumentationFileDisabledWithoutFile.csproj
projects/GenerateDocumentationFileEnabled/GenerateDocumentationFileEnabled.csproj
projects/GenerateDocumentationFileEnabledWithFile/GenerateDocumentationFileEnabledWithFile.csproj
projects/GenerateDocumentationFileMissing/GenerateDocumentationFileMissing.csproj
projects/GenerateDocumentationFileMissingWithEmptyFile/GenerateDocumentationFileMissingWithEmptyFile.csproj
projects/GenerateDocumentationFileMissingWithFile/GenerateDocumentationFileMissingWithFile.csproj
specs/DotNetProjectFile.Analyzers.Specs/Rules/MS_Build/Generate_documentation_file.cs
src/DotNetProjectFile.Analyzers/Analyzers/MsBuild/EnableGenerateDocumentationFile.cs
src/DotNetProjectFile.Analyzers/DotNetProjectFile.Analyzers.csproj
src/DotNetProjectFile.Analyzers/MsBuild/DocumentationFile.cs
src/DotNetProjectFile.Analyzers/MsBuild/GenerateDocumentationFile.cs
src/DotNetProjectFile.Analyzers/README.md
src/DotNetProjectFile.Analyzers/Rule.cs

Proj0244: Generate documentation file

---

specs/DotNetProjectFile.Analyzers.Specs/Design_specs.cs

Fix broken ``have_mark_down_documentation` tests

---

src/DotNetProjectFile.Analyzers.Sdk/DotNetProjectFile.Analyzers.Sdk.csproj
src/DotNetProjectFile.Analyzers.Sdk/DotNetProjectFile.Analyzers.Sdk.props
src/DotNetProjectFile.Analyzers.Sdk/DotNetProjectFile.Analyzers.Sdk.targets
src/DotNetProjectFile.Analyzers/DotNetProjectFile.Analyzers.csproj

It is about time. We now can ship over 100 rules!

Release v1.5.6

---

specs/DotNetProjectFile.Analyzers.Specs/Extensions/Microsoft.CodeAnalysis.Diagnostics.DiagnosticAnalyzer.cs
specs/DotNetProjectFile.Analyzers.Specs/Rules/MS_Build/Use_analyzers_for_packages.cs
src/DotNetProjectFile.Analyzers/Analyzers/MsBuild/EnableApiCompatibilityAttributeChecks.cs
src/DotNetProjectFile.Analyzers/Analyzers/MsBuild/UseAnalyzersForPackages.cs
src/DotNetProjectFile.Analyzers/DotNetProjectFile.Analyzers.csproj
src/DotNetProjectFile.Analyzers/NuGet/Analyzer.cs

Proj1001: Take <GlobalPackageReference>'s also into account

---

specs/DotNetProjectFile.Analyzers.Specs/Licensing/Url_specs.cs
src/DotNetProjectFile.Analyzers/Extensions/System.String.cs
src/DotNetProjectFile.Analyzers/Licensing/Licenses.cs

License URL parsing

---

README.md
projects/NoAuthors/NoAuthors.csproj
projects/NoCopyright/NoCopyright.csproj
projects/NoDescription/NoDescription.csproj
projects/NoIcon/NoIcon.csproj
projects/NoIconUrl/NoIconUrl.csproj
projects/NoLicense/NoLicense.csproj
projects/NoPackageRequireLicenseAcceptance/NoPackageRequireLicenseAcceptance.csproj
projects/NoReadme/NoReadme.csproj
projects/NoReleaseNotes/NoReleaseNotes.csproj
projects/NoRepositoryUrl/NoRepositoryUrl.csproj
projects/NoTags/NoTags.csproj
projects/NoUrl/NoUrl.csproj
projects/NoVersion/NoVersion.csproj
projects/PackageDescription/PackageDescription.csproj
projects/PackageRequireLicenseAcceptanceDisabled/PackageRequireLicenseAcceptanceDisabled.csproj
projects/VersionPrefix/VersionPrefix.csproj
projects/VersionPrefixAndSuffix/VersionPrefixAndSuffix.csproj
projects/VersionPrefixAndSuffixAndVersion/VersionPrefixAndSuffixAndVersion.csproj
projects/WithLicenseFile/WithLicenseFile.csproj
specs/DotNetProjectFile.Analyzers.Specs/Rules/MS_Build/NuGet packages/Define_package_info.cs
src/DotNetProjectFile.Analyzers.Sdk/DotNetProjectFile.Analyzers.Sdk.csproj
src/DotNetProjectFile.Analyzers/Analyzers/MsBuild/DefinePackageInfo.cs
src/DotNetProjectFile.Analyzers/DotNetProjectFile.Analyzers.csproj
src/DotNetProjectFile.Analyzers/MsBuild/PackageRequireLicenseAcceptance.cs
src/DotNetProjectFile.Analyzers/README.md
src/DotNetProjectFile.Analyzers/Rule.cs

Proj0217: Define requiring license acceptance explicitly

---

specs/DotNetProjectFile.Analyzers.Specs/Rules/MS_Build/Exclude_private_asset_dependencies.cs
src/DotNetProjectFile.Analyzers/NuGet/PackageCache.cs

Investigate non-reproducable issue

---

projects/TUnitTestProject/TUnitTestProject.csproj
specs/DotNetProjectFile.Analyzers.Specs/Rules/MS_Build/Test projects/TUnit_usage.cs
src/DotNetProjectFile.Analyzers/Analyzers/MsBuild/TUnitUsage.cs
src/DotNetProjectFile.Analyzers/Analyzers/MsBuild/TestProjectsRequireSdk.cs
src/DotNetProjectFile.Analyzers/DotNetProjectFile.Analyzers.csproj
src/DotNetProjectFile.Analyzers/NuGet/Packages.cs
src/DotNetProjectFile.Analyzers/README.md
src/DotNetProjectFile.Analyzers/Rule.cs

Documentation PR: https://github.com/dotnet-project-file-analyzers/dotnet-project-file-analyzers.github.io/pull/94
Closes #294 
Closes #295

Proj1103 and Proj1104 about TUnit usage

---

specs/DotNetProjectFile.Analyzers.Specs/Rules/MS_Build/Remove_deprecated_RestoreProjectStyle.cs
specs/DotNetProjectFile.Analyzers.Specs/Rules/MS_Build/Remove_deprecated_estoreProjectStyle.cs
src/DotNetProjectFile.Analyzers/Analyzers/MsBuild/RemoveDeprecatedRestoreProjectStyle.cs
src/DotNetProjectFile.Analyzers/DotNetProjectFile.Analyzers.csproj
src/DotNetProjectFile.Analyzers/MsBuild/RestoreProjectStyle.cs
src/DotNetProjectFile.Analyzers/README.md
src/DotNetProjectFile.Analyzers/Rule.cs

Proj0035: Remove deprecated RestoreProjectStyle property

---

.net.csproj
projects/CPMWithUnusedPackageVersions/.net.csproj
projects/CPMWithUnusedPackageVersions/CPMWithUnusedPackageVersions.csproj
projects/CPMWithUnusedPackageVersions/Directory.Packages.props
specs/DotNetProjectFile.Analyzers.Specs/Design_specs.cs
specs/DotNetProjectFile.Analyzers.Specs/Rules/MS_Build/CPM/Remove_unused_package_versions.cs
src/DotNetProjectFile.Analyzers.Sdk/DotNetProjectFile.Analyzers.Sdk.csproj
src/DotNetProjectFile.Analyzers.Sdk/DotNetProjectFile.Analyzers.Sdk.props
src/DotNetProjectFile.Analyzers/Analyzers/MsBuild/RemoveUnusedPackageVersions.cs
src/DotNetProjectFile.Analyzers/CodeAnalysis/ProjectFiles.cs
src/DotNetProjectFile.Analyzers/DotNetProjectFile.Analyzers.csproj
src/DotNetProjectFile.Analyzers/MsBuild/Project.cs
src/DotNetProjectFile.Analyzers/MsBuild/ProjectFileType.cs
src/DotNetProjectFile.Analyzers/MsBuild/ProjectFileTypes.cs
src/DotNetProjectFile.Analyzers/README.md
src/DotNetProjectFile.Analyzers/Rule.cs
src/DotNetProjectFile.Analyzers/build/DotNetProjectFile.Analyzers.props

Proj0810: Remove unused package versions

---

specs/DotNetProjectFile.Analyzers.Specs/.globalconfig
specs/DotNetProjectFile.Analyzers.Specs/Design_specs.cs
specs/DotNetProjectFile.Analyzers.Specs/Extensions/Microsoft.CodeAnalysis.Diagnostics.DiagnosticAnalyzer.cs
specs/DotNetProjectFile.Analyzers.Specs/Licensing/Spdx_generator.cs
specs/DotNetProjectFile.Analyzers.Specs/Rules/MS_Build/Thrid_Party_license_compliance.cs

Violating RS1035 is no concern in a specs project

---

projects/DotnetProjectFilesSdk/.net.csproj
specs/DotNetProjectFile.Analyzers.Specs/Design_specs.cs
specs/DotNetProjectFile.Analyzers.Specs/DotNetProjectFile.Analyzers.Specs.csproj
specs/DotNetProjectFile.Analyzers.Specs/FluentAssertions/DiagnosticAnalyzerAssertions.cs
specs/DotNetProjectFile.Analyzers.Specs/FluentAssertions/DiagnosticsAssertions.cs

Use AwesomeAssertions

---

specs/DotNetProjectFile.Analyzers.Specs/NuGet/NuGet_config_file_specs.cs
src/DotNetProjectFile.Analyzers/NuGet/Packaging/NuGetConfigFile.cs
src/DotNetProjectFile.Analyzers/NuGet/Packaging/NuGetConfigKeyValue.cs
src/DotNetProjectFile.Analyzers/NuGet/Packaging/NuGetConfigSection.cs

Resolve nuget.config globalPackagesFolder

---

specs/DotNetProjectFile.Analyzers.Specs/NuGet/Nuspec_file_specs.cs
src/DotNetProjectFile.Analyzers/NuGet/Packaging/Metadata.cs
src/DotNetProjectFile.Analyzers/NuGet/Packaging/NuSpecFile.cs
src/DotNetProjectFile.Analyzers/NuGet/Packaging/NuspecDepedencies.cs
src/DotNetProjectFile.Analyzers/NuGet/Packaging/NuspecDependency.cs

Resolve dependencies Nuspec file

---

specs/Benchmarks/Licening.cs
specs/Benchmarks/Program.cs
specs/Benchmarks/README.md
specs/DotNetProjectFile.Analyzers.Specs/Licensing/Url_specs.cs
src/DotNetProjectFile.Analyzers/Licensing/Licenses.cs

By mistake (only) two flavors where supported. This has been solved now.

Support mit-license.org

---

specs/DotNetProjectFile.Analyzers.Specs/Rules/MS_Build/Remove_None_when_redundant.cs
src/DotNetProjectFile.Analyzers/Analyzers/MsBuild/NoneItemWithRemoveIsRedudent.cs
src/DotNetProjectFile.Analyzers/Analyzers/MsBuild/RemoveNoneWhenRedundant.cs
src/DotNetProjectFile.Analyzers/DotNetProjectFile.Analyzers.csproj
src/DotNetProjectFile.Analyzers/README.md
src/DotNetProjectFile.Analyzers/Rule.cs

Proj0036: Remove None when redundant

---

specs/DotNetProjectFile.Analyzers.Specs/Rules/MS_Build/Exclude_private_asset_dependencies.cs
src/DotNetProjectFile.Analyzers/Analyzers/MsBuild/ExcludePrivateAssetDependencies.cs
src/DotNetProjectFile.Analyzers/DotNetProjectFile.Analyzers.csproj
src/DotNetProjectFile.Analyzers/NuGet/CachedPackage.cs
src/DotNetProjectFile.Analyzers/NuGet/PackageCache.cs

Fix packages with deps incorrectly marked as development dependencies

---

specs/DotNetProjectFile.Analyzers.Specs/Rules/MS_Build/Generate_documentation_file.cs
src/DotNetProjectFile.Analyzers/Analyzers/MsBuild/EnableGenerateDocumentationFile.cs
src/DotNetProjectFile.Analyzers/DotNetProjectFile.Analyzers.csproj

Proj0244: Exclude development dependencies

---

.github/workflows/build-test.yaml
props/common.props
specs/Benchmarks/Benchmarks.csproj
specs/DotNetProjectFile.Analyzers.Specs/DotNetProjectFile.Analyzers.Specs.csproj
specs/DotNetProjectFile.Analyzers.Specs/Rules/All.cs
src/DotNetProjectFile.Analyzers.Sdk/DotNetProjectFile.Analyzers.Sdk.csproj
src/DotNetProjectFile.Analyzers/DotNetProjectFile.Analyzers.csproj

It seems that while building, somethings goes wrong related to generating the SBOM or some other side process. This PR is find out what is causing this issue, and how to fix it.

Investigate failing builds

---

projects/ConfigFilesExistence/ConfigFilesExistence.csproj
projects/ConfigFilesExistence/analyzers-config.ini
projects/ConfigFilesExistence/editor-config.ini
specs/DotNetProjectFile.Analyzers.Specs/Rules/MS_Build/Build_action_include_should_exist.cs
src/DotNetProjectFile.Analyzers/DotNetProjectFile.Analyzers.csproj
src/DotNetProjectFile.Analyzers/MsBuild/BuildAction.cs
src/DotNetProjectFile.Analyzers/MsBuild/EditorConfgFiles.cs
src/DotNetProjectFile.Analyzers/MsBuild/GlobalAnalyzerConfigFiles.cs

Proj0022: Include <EditorConfig> and <GlobalAnalyzerConfigFiles> as build actions

---

globalconfig.verified.txt
projects/CompliantCSharp/CompliantCSharp.csproj
projects/PublishableWebApp/Program.cs
projects/PublishableWebApp/PublishableWebApp.csproj
specs/DotNetProjectFile.Analyzers.Specs/Rules/MS_Build/Publish_executables_only.cs
src/DotNetProjectFile.Analyzers/Analyzers/MsBuild/DefineOutputType.cs
src/DotNetProjectFile.Analyzers/Analyzers/MsBuild/PublishExeOnly.cs
src/DotNetProjectFile.Analyzers/DotNetProjectFile.Analyzers.csproj
src/DotNetProjectFile.Analyzers/MsBuild/Project.Property.cs
src/DotNetProjectFile.Analyzers/README.md
src/DotNetProjectFile.Analyzers/Rule.cs

Linked documentation: https://github.com/dotnet-project-file-analyzers/dotnet-project-file-analyzers.github.io/pull/111
Closes #403

Proj0401: Only publish executables

---

specs/DotNetProjectFile.Analyzers.Specs/Properties/GlobalUsings.cs
specs/DotNetProjectFile.Analyzers.Specs/Rules/MS_Build/Enable_continuous_integration_build.cs
specs/DotNetProjectFile.Analyzers.Specs/Rules/MS_Build/Enable_restore_locked_mode.cs
specs/DotNetProjectFile.Analyzers.Specs/TestTools/BuildAgentHelpers.cs
src/DotNetProjectFile.Analyzers/Analyzers/MsBuild/EnableContinuousIntegrationBuild.cs
src/DotNetProjectFile.Analyzers/Analyzers/MsBuild/EnableRestoreLockedMode.cs
src/DotNetProjectFile.Analyzers/BuildAgents/BuildAgent.cs
src/DotNetProjectFile.Analyzers/Caching/EnumCache.cs
src/DotNetProjectFile.Analyzers/DotNetProjectFile.Analyzers.csproj
src/DotNetProjectFile.Analyzers/Extensions/DotNetProjectFile.MsBuild.Node.cs

Proj0044 Allow CI conditionals

---

specs/DotNetProjectFile.Analyzers.Specs/Rules/MS_Build/Run_NuGet_security_audits_on_all.cs
src/DotNetProjectFile.Analyzers/DotNetProjectFile.Analyzers.csproj
src/DotNetProjectFile.Analyzers/Rule.cs

Bug fix Proj0040 NugetAuditMode -> NuGetAuditMode

---

.net.csproj
README.md
docs/general/.net.csproj
docs/general/sdk.md
specs/DotNetProjectFile.Analyzers.Specs/Design_specs.cs

While at it, also update the link to the rule documentation from the root `README.md`.

Add .net.csproj SDK example

---

docs/README.md
docs/rules/Proj0046.md
globalconfig.verified.txt
specs/DotNetProjectFile.Analyzers.Specs/Rules/MS_Build/Update_should_change_state.cs
src/DotNetProjectFile.Analyzers/Analyzers/MsBuild/UpdateShouldChangeState.cs
src/DotNetProjectFile.Analyzers/DotNetProjectFile.Analyzers.csproj
src/DotNetProjectFile.Analyzers/README.md
src/DotNetProjectFile.Analyzers/Rule.cs

Proj0046: Update statements should change state

---

docs/rules/Proj1100.md
docs/rules/Proj1101.md
docs/rules/Proj1102.md
docs/rules/Proj1103.md
docs/rules/Proj1104.md

Drop BOM for documentation

---

docs/README.md
docs/rules/Proj0219.md
globalconfig.verified.txt
specs/DotNetProjectFile.Analyzers.Specs/Rules/MS_Build/Packables_should_be_libraries.cs
src/DotNetProjectFile.Analyzers/Analyzers/MsBuild/PackablesShouldBeLibraries.cs
src/DotNetProjectFile.Analyzers/DotNetProjectFile.Analyzers.csproj
src/DotNetProjectFile.Analyzers/README.md
src/DotNetProjectFile.Analyzers/Rule.cs

Proj0219: Packable projects should be libraries

---

docs/README.md
docs/rules/Proj5001.md
globalconfig.verified.txt
projects/RemoveSlnFiles/.net.csproj
projects/RemoveSlnFiles/remove-sln-files.sln
projects/RemoveSlnFiles/remove-sln-files.slnx
specs/DotNetProjectFile.Analyzers.Specs/Rules/SLNX/Remove_SLN_files.cs
src/DotNetProjectFile.Analyzers/Analyzers/Generic/OnlyUseUTF8WithoutBom.cs
src/DotNetProjectFile.Analyzers/Analyzers/Slnx/UseSlnxFiles.cs
src/DotNetProjectFile.Analyzers/DotNetProjectFile.Analyzers.csproj
src/DotNetProjectFile.Analyzers/IO/IOFile.cs
src/DotNetProjectFile.Analyzers/README.md
src/DotNetProjectFile.Analyzers/Rule.SLNX.cs

Proj5001: remove sln project file

---

README.md

Additional files are automatically added for a while now, adding files explicitly is not longer needed.

Additional files are automatically added
