README.md, build.sln, dotnet-project-file-analyzers.sln, projects/CompliantCSharp/CompliantCSharp.csproj, projects/CompliantVB/CompliantVB.vbproj, projects/DisabledNugetAudit/DisabledNugetAudit.csproj, projects/DisabledNugetAudit/Placeholder.cs, projects/NoNugetAudit/NoNugetAudit.csproj, projects/NoNugetAudit/Placeholder.cs, rules/Proj0004.md, specs/DotNetProjectFile.Analyzers.Specs/Rules/Run_NuGet_security_audits_automatically.cs, src/DotNetProjectFile.Analyzers/Analyzers/RunNuGetSecurityAuditsAutomatically.cs, src/DotNetProjectFile.Analyzers/Diagnostics/Category.cs, src/DotNetProjectFile.Analyzers/Extensions/System.Linq.Enumerable.cs, src/DotNetProjectFile.Analyzers/README.md, src/DotNetProjectFile.Analyzers/Rule.cs, src/DotNetProjectFile.Analyzers/Xml/Node.cs, src/DotNetProjectFile.Analyzers/Xml/NuGetAudit.cs, src/DotNetProjectFile.Analyzers/Xml/PropertyGroup.cs
Once enabled, GitHub's vulnerability database is consulted to check for security issues that come with using any of the referenced packages.
More information: https://learn.microsoft.com/en-us/nuget/concepts/auditing-packages
``` XML
<TargetFramework>net7.0</TargetFramework>
</Project>
```
``` XML
<TargetFramework>net7.0</TargetFramework>
<NuGetAudit>true</NuGetAudit>
</Project>
```
=> New Rule Proj0004: Run NuGet security audits automatically

build.sln, dotnet-project-file-analyzers.sln, projects/LegacyProject/LegacyProject.csproj, projects/PackageReferenceAssetsAsAttributes/PackageReferenceAssetsAsAttributes.csproj, projects/PackageReferenceAssetsAsAttributes/Placeholder.cs, projects/PackageReferenceAssetsAsElements/PackageReferenceAssetsAsElements.csproj, projects/PackageReferenceAssetsAsElements/Placeholder.cs, rules/Proj0005.md, specs/DotNetProjectFile.Analyzers.Specs/Rules/Define_package_reference_assets_as_attributes.cs, src/DotNetProjectFile.Analyzers/Analyzers/DefinePackageReferenceAssetsAsAttributes.cs, src/DotNetProjectFile.Analyzers/Diagnostics/ProjectFileAnalysisContext.cs, src/DotNetProjectFile.Analyzers/Extensions/System.String.cs, src/DotNetProjectFile.Analyzers/Rule.cs
You might want to control the [dependency assets](https://learn.microsoft.com/en-us/nuget/consume-packages/package-references-in-project-files#controlling-dependency-assets)
of the package reference, and define its preferences. For readability purposes,
it is preferred to define `PrivateAssets`, `IncludeAssets`, and `PrivateAsssets`
as XML attributes, instead of XML elements.
``` XML
<ItemGroup Label="Analyzer">
<ProjectReference Include="DotNetProjectFile.Analyzers">
<PrivateAssets>all</PrivateAssets>
<IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
</ItemGroup>
</Project>
```
``` XML
<ItemGroup Label="Analyzer">
<ProjectReference Include="DotNetProjectFile.Analyzers" …
```
=> New Rule Proj0005: Define package reference assets as attributes

README.md, dotnet-project-file-analyzers.sln, projects/EmptyNodes/EmptyNodes.csproj, projects/EmptyNodes/Palceholder.cs, rules/Proj0007.md, specs/DotNetProjectFile.Analyzers.Specs/Rules/Remove_empty_nodes.cs, src/DotNetProjectFile.Analyzers/Analyzers/RemoveEmptyNodes.cs, src/DotNetProjectFile.Analyzers/DotNetProjectFile.Analyzers.csproj, src/DotNetProjectFile.Analyzers/README.md, src/DotNetProjectFile.Analyzers/Rule.cs, src/DotNetProjectFile.Analyzers/Xml/Node.cs, src/DotNetProjectFile.Analyzers/Xml/Nodes.cs
Empty nodes only add noise, as they contain no information.
``` XML
<PropertyGroup />
<ItemGroup>
</ItemGroup>
</Project>
```
``` XML
<TargetFramework>net7.0</TargetFramework>
<ItemGroup>
<ProjectReference Include="DotNetProjectFile.Analyzers" PrivateAssets="all" IncludeAssets="runtime; build; native; contentfiles; analyzers; buildtransitive" />	
</ItemGroup>
</Project>
```
=> New Rule Proj0007: Remove empty nodes

README.md, dotnet-project-file-analyzers.sln, projects/FolderNodes/FolderNodes.csproj, projects/FolderNodes/Placeholder.cs, rules/Proj0005.md, rules/Proj0008.md, specs/DotNetProjectFile.Analyzers.Specs/Rules/Remove_empty_nodes.cs, specs/DotNetProjectFile.Analyzers.Specs/Rules/Remove_folder_nodes.cs, src/DotNetProjectFile.Analyzers/Analyzers/RemoveFolderNodes.cs, src/DotNetProjectFile.Analyzers/DotNetProjectFile.Analyzers.csproj, src/DotNetProjectFile.Analyzers/README.md, src/DotNetProjectFile.Analyzers/Rule.cs, src/DotNetProjectFile.Analyzers/Xml/Folder.cs, src/DotNetProjectFile.Analyzers/Xml/ItemGroup.cs, src/DotNetProjectFile.Analyzers/Xml/Node.cs
Folders nodes only add noise. They are leftovers of directories created in the
IDE; allowing to show the folder while it does not contain a file relevant for
the .NET project yet. This should only exist temporarily.
``` XML
<ItemGroup>
<Folder Include="SomeFolder\" />
</ItemGroup>
</Project>
```
``` XML
</Project>
```
=> New Rule Proj0008: Remove folder nodes

README.md, build.sln, dotnet-project-file-analyzers.sln, projects/TargetFrameworksMultiple/Placeholder.cs, projects/TargetFrameworksMultiple/TargetFrameworksMultiple.csproj, projects/TargetFrameworksSingle/Placeholder.cs, projects/TargetFrameworksSingle/TargetFrameworksSingle.csproj, rules/Proj0009.md, specs/DotNetProjectFile.Analyzers.Specs/Rules/Define_single_target_framework.cs, src/DotNetProjectFile.Analyzers/Analyzers/DefineSingleTargetFramework.cs, src/DotNetProjectFile.Analyzers/Analyzers/RemoveEmptyNodes.cs, src/DotNetProjectFile.Analyzers/Analyzers/RunNuGetSecurityAuditsAutomatically.cs, src/DotNetProjectFile.Analyzers/DotNetProjectFile.Analyzers.csproj, src/DotNetProjectFile.Analyzers/README.md, src/DotNetProjectFile.Analyzers/Rule.cs, src/DotNetProjectFile.Analyzers/Xml/Folder.cs, src/DotNetProjectFile.Analyzers/Xml/Import.cs, src/DotNetProjectFile.Analyzers/Xml/ItemGroup.cs, src/DotNetProjectFile.Analyzers/Xml/Node.cs, src/DotNetProjectFile.Analyzers/Xml/Nodes.cs, src/DotNetProjectFile.Analyzers/Xml/PackageReference.cs, src/DotNetProjectFile.Analyzers/Xml/Project.cs, src/DotNetProjectFile.Analyzers/Xml/PropertyGroup.cs, src/DotNetProjectFile.Analyzers/Xml/TargetFramework.cs, src/DotNetProjectFile.Analyzers/Xml/TargetFrameworks.cs
To prevent confusion, only use the TargetFrameworks node when there are
multiple target frameworks. Otherwise use the TargetFramework node.
``` XML
<TargetFrameworks>net7.0</TargetFrameworks>
</Project>
```
``` XML
<TargetFramework>net7.0</TargetFramework>
</Project>
```
=> New Rule Proj0009: Use the TragetFramework node for a single target framework

src/DotNetProjectFile.Analyzers/Analyzers/MsBuild/AddAdditionalFile.cs, src/DotNetProjectFile.Analyzers/Analyzers/MsBuild/DefinePackageReferenceAssetsAsAttributes.cs, src/DotNetProjectFile.Analyzers/Analyzers/MsBuild/DefineSingleTargetFramework.cs, src/DotNetProjectFile.Analyzers/Analyzers/MsBuild/DefineUsingsExplicit.cs, src/DotNetProjectFile.Analyzers/Analyzers/MsBuild/RemoveEmptyNodes.cs, src/DotNetProjectFile.Analyzers/Analyzers/MsBuild/RemoveFolderNodes.cs, src/DotNetProjectFile.Analyzers/Analyzers/MsBuild/RunNuGetSecurityAuditsAutomatically.cs, src/DotNetProjectFile.Analyzers/Analyzers/MsBuild/UseAnalyzers.cs, src/DotNetProjectFile.Analyzers/Analyzers/MsBuild/UseAnalyzersForPackages.cs, src/DotNetProjectFile.Analyzers/Diagnostics/ProjectFileAnalysisContext.cs, src/DotNetProjectFile.Analyzers/Extensions/Microsoft.CodeAnalysis.Diagnostics.AnalysisContext.cs, src/DotNetProjectFile.Analyzers/MsBuild/Import.cs, src/DotNetProjectFile.Analyzers/MsBuild/Project.cs, src/DotNetProjectFile.Analyzers/MsBuild/Projects.cs
For each resolved MS Build project file the ProjectFileAnalysisContext is triggered, instead of requiring rules to call `.AncestorsAndSelf()`.
=> Trigger ProjectFileAnalysisContext for projects and linked props

README.md, dotnet-project-file-analyzers.sln, projects/ResxMissingInvariant/Chess.de-AT.resx, projects/ResxMissingInvariant/Chess.nl.resx, projects/ResxMissingInvariant/Chess.resx, projects/ResxMissingInvariant/Placeholder.cs, projects/ResxMissingInvariant/ResxMissingInvariant.csproj, rules/Proj2004.md, specs/DotNetProjectFile.Analyzers.Specs/Rules/RESX/Add_invariant_fallback_values.cs, src/DotNetProjectFile.Analyzers/Analyzers/Resx/AddInvariantFallbackValues.cs, src/DotNetProjectFile.Analyzers/DotNetProjectFile.Analyzers.csproj, src/DotNetProjectFile.Analyzers/Extensions/System.Globalization.CultureInfo.cs, src/DotNetProjectFile.Analyzers/README.md, src/DotNetProjectFile.Analyzers/Resx/Resource.cs, src/DotNetProjectFile.Analyzers/Rule.cs
To ensure that localized values can be resolved, a localized value must have a culture invariant alternative.
See: https://learn.microsoft.com/en-us/dotnet/core/extensions/localization
See #31
=> New Rule Proj2004: Add invariant fallback value

specs/DotNetProjectFile.Analyzers.Specs/Rules/MS_Build/Avoid_license_url.cs, src/DotNetProjectFile.Analyzers/Analyzers/MsBuild/AvoidLicenseUrl.cs
By reporting on node, the IDE will navigate the user directly to the node to change.
=> Report obsolete <PackageLicenseUrl> on on node

src/DotNetProjectFile.Analyzers/Analyzers/MsBuild/DefinePackageInfo.cs, src/DotNetProjectFile.Analyzers/MsBuild/MsBuildDefaults.cs, src/DotNetProjectFile.Analyzers/MsBuild/Project.cs
Given the default of MS Build and what can be defined in the project, of any of its imports, it can be precisely determined if a project IsPackable or not.
=> Use Property() on project to determine if a packabillity

.editorconfig, README.md, dotnet-project-file-analyzers.sln, projects/CompliantCSharpPackage/CompliantCSharpPackage.csproj, projects/NoAuthors/NoAuthors.csproj, projects/NoCopyright/NoCopyright.csproj, projects/NoDescription/NoDescription.csproj, projects/NoIcon/NoIcon.csproj, projects/NoIconUrl/NoIconUrl.csproj, projects/NoLicense/NoLicense.csproj, projects/NoReadme/NoReadme.csproj, projects/NoReleaseNotes/NoReleaseNotes.csproj, projects/NoRepositoryUrl/NoRepositoryUrl.csproj, projects/NoTags/NoTags.csproj, projects/NoUrl/NoUrl.csproj, projects/NoVersion/NoVersion.csproj, projects/WithLicenseFile/WithLicenseFile.csproj, rules/Proj0214.md, specs/DotNetProjectFile.Analyzers.Specs/Rules/MS_Build/Define_package_info.cs, src/DotNetProjectFile.Analyzers/Analyzers/MsBuild/DefinePackageInfo.cs, src/DotNetProjectFile.Analyzers/DotNetProjectFile.Analyzers.csproj, src/DotNetProjectFile.Analyzers/MsBuild/PackageId.cs, src/DotNetProjectFile.Analyzers/MsBuild/PropertyGroup.cs, src/DotNetProjectFile.Analyzers/README.md, src/DotNetProjectFile.Analyzers/Rule.cs
To ensure the creation of well-formed packages, explicitly define the `<PackageID>` node or disable package generation by defining the `<IsPackable>` node with value `false`.
``` XML
<TargetFramework>net7.0</TargetFramework>
<IsPackable>true</IsPackable>
</Project>
```
``` XML
<TargetFramework>net7.0</TargetFramework>
<IsPackable>true</IsPackable>
<PackableId>NuGetPackageId</PackableId>
</Project>
```
Or
``` XML
<TargetFramework>net7.0</TargetFramework>
<PackableId>false</PackableId>
</Project>
```
#16
=> New rule Proj0214: Define the NuGet project ID explicitly

src/DotNetProjectFile.Analyzers/Analyzers/MsBuild/DefineIsPackable.cs, src/DotNetProjectFile.Analyzers/Analyzers/MsBuild/DefineOutputType.cs, src/DotNetProjectFile.Analyzers/Analyzers/MsBuild/DefinePackageInfo.cs, src/DotNetProjectFile.Analyzers/Analyzers/MsBuild/RunNuGetSecurityAuditsAutomatically.cs, src/DotNetProjectFile.Analyzers/Analyzers/MsBuild/UseAnalyzers.cs, src/DotNetProjectFile.Analyzers/Analyzers/MsBuild/UseAnalyzersForPackages.cs, src/DotNetProjectFile.Analyzers/Analyzers/MsBuild/UseSonarAnalyzers.cs, src/DotNetProjectFile.Analyzers/Analyzers/MsBuildProjectFileAnalyzer.cs, src/DotNetProjectFile.Analyzers/MsBuild/MsBuildDefaults.cs
There are rules (like `DefineOutputType`) that only on the MS Build project file, and not to the imported props. With this `ApplyToProps` property (default is `true`) this can be done in a better readable way.
=> Introduction of ApplyToProps

README.md, dotnet-project-file-analyzers.sln, projects/DoublePackageReferences/DoublePackageReferences.csproj, projects/DoublePackageReferences/Placeholder.cs, projects/props/DoublePackageReferences.props, rules/Proj0012.md, rules/Proj0013.md, specs/DotNetProjectFile.Analyzers.Specs/Rules/MS_Build/Include_package_references_once.cs, src/DotNetProjectFile.Analyzers/Analyzers/MsBuild/IncludePackageReferencesOnce.cs, src/DotNetProjectFile.Analyzers/DotNetProjectFile.Analyzers.csproj, src/DotNetProjectFile.Analyzers/MsBuild/PackageReference.cs, src/DotNetProjectFile.Analyzers/README.md, src/DotNetProjectFile.Analyzers/Rule.cs
A `<PackageReference>` should only be defined once per package. If (for whatever
reason) an update is needed in project file, the `Update` attribute should be
used. Update are only allowed in different files.
``` XML
<Project>
<ItemGroup>
<PackageReference Include="Qowaiv" Version="6.0.0" />
</ItemGroup>
</Project>
```
``` XML
<ItemGroup>
<PackageReference Include="Qowaiv" Version="6.4.2" />
<PackageReference Include="serilog" Version="2.10.0" />
<PackageReference Include="serilog" Version="3.0.1" />
</ItemGroup>
</Project>
```
``` XML
<Project>
<ItemGroup>
<PackageReference Include="Qowaiv" Version="6.0.0" />
</ItemGroup>
</Project>
```
``` XML
<ItemGroup>
<PackageReference Update="Qowaiv" Version="6.4.2" /> …
```
=> New rule Proj0013: Include package references once

build.sln, dotnet-project-file-analyzers.sln, projects/ChooseWhen/ChooseWhen.csproj, projects/ChooseWhen/Placeholder.cs, specs/DotNetProjectFile.Analyzers.Specs/DotNetProjectFile.Analyzers.Specs.csproj, specs/DotNetProjectFile.Analyzers.Specs/MS_Build/Choose_specs.cs, specs/DotNetProjectFile.Analyzers.Specs/Properties/GlobalUsings.cs, src/DotNetProjectFile.Analyzers/Analyzers/MsBuild/DefinePropertiesOnce.cs, src/DotNetProjectFile.Analyzers/Analyzers/MsBuild/ReassignPropertiesWithDifferentValue.cs, src/DotNetProjectFile.Analyzers/Analyzers/MsBuild/RemoveEmptyNodes.cs, src/DotNetProjectFile.Analyzers/DotNetProjectFile.Analyzers.csproj, src/DotNetProjectFile.Analyzers/MsBuild/Choose.cs, src/DotNetProjectFile.Analyzers/MsBuild/ItemGroup.cs, src/DotNetProjectFile.Analyzers/MsBuild/Node.cs, src/DotNetProjectFile.Analyzers/MsBuild/Nodes.cs, src/DotNetProjectFile.Analyzers/MsBuild/Otherwise.cs, src/DotNetProjectFile.Analyzers/MsBuild/Project.cs, src/DotNetProjectFile.Analyzers/MsBuild/PropertyGroup.cs, src/DotNetProjectFile.Analyzers/MsBuild/When.cs, src/DotNetProjectFile.Analyzers/Rule.cs
Because besides `@Condition`, also `<Choose>` containing `<When>` and `<Otherwise>` can be used to add `<PropertyGroup>`, and  `<ItemGroup>` conditionally, their children should be members of `Project.PropertyGroups` and `Propject.ItemGroups`.
See: #21
=> Improvement: Support choose

dotnet-project-file-analyzers.sln, projects/PackageDescription/PackageDescription.csproj, projects/PackageDescription/Placeholder.cs, specs/DotNetProjectFile.Analyzers.Specs/Rules/MS_Build/Define_package_info.cs, src/DotNetProjectFile.Analyzers/Analyzers/MsBuild/DefinePackageInfo.cs, src/DotNetProjectFile.Analyzers/DotNetProjectFile.Analyzers.csproj, src/DotNetProjectFile.Analyzers/MsBuild/Nodes.T.cs, src/DotNetProjectFile.Analyzers/MsBuild/Nodes.cs, src/DotNetProjectFile.Analyzers/MsBuild/PackageDescription.cs, src/DotNetProjectFile.Analyzers/MsBuild/PropertyGroup.cs, src/DotNetProjectFile.Analyzers/Rule.cs
Using `<PackageDescription>` and `<Description>` both give the desired result.
See: https://github.com/dotnet-project-file-analyzers/dotnet-project-file-analyzers.github.io/pull/1
=> FP Proj0202: Support both <Description> and <PackageDescription>

src/DotNetProjectFile.Analyzers/DotNetProjectFile.Analyzers.csproj
Use the oldest version possible to prevent issues with other Roslyn tooling.
=> Downgrade version Roslyn dependency

src/DotNetProjectFile.Analyzers/DotNetProjectFile.Analyzers.csproj
By suppressing dependencies, the package will not longer contain a fixed dependency on `Microsoft.CodeAnalysis.Workspaces.Common`. This should prevent issues with solutions that have a dependency on `Microsoft.CodeAnalysis.Workspaces.Common` on their own.
Other analyzer projects don't seem to have that dependency either specified: 
- [SerilogAnalyze](https://www.nuget.org/packages/SerilogAnalyzer/0.15.0#dependencies-body-tab)
- [SonarAnalyzer.CSharp](https://www.nuget.org/packages/SonarAnalyzer.CSharp/9.6.0.74858#dependencies-body-tab)
=> Suppress dependencies when packing

specs/DotNetProjectFile.Analyzers.Specs/DotNetProjectFile.Analyzers.Specs.csproj, specs/DotNetProjectFile.Analyzers.Specs/IO/File_path_compare.cs, src/DotNetProjectFile.Analyzers/DotNetProjectFile.Analyzers.csproj, src/DotNetProjectFile.Analyzers/IO/FilePathComparer.cs
The actual unit test for this scenario did not check the order, just if the two members are in the set. (Oops)
=> FN & FP: Fix sorting check

specs/DotNetProjectFile.Analyzers.Specs/IO/File_path_compare.cs, specs/DotNetProjectFile.Analyzers.Specs/MS_Build/Choose_specs.cs, src/DotNetProjectFile.Analyzers/DotNetProjectFile.Analyzers.csproj, src/DotNetProjectFile.Analyzers/IO/FilePathComparer.cs
The following should be compliant:
``` XML
<PackageReference Include="CodeAnalysis.TestTools" Version="1.1.0" />
<PackageReference Include="coverlet.collector" Version="*" PrivateAssets="all" />
````
=> FP/FN: Sorting of referencese should be case insensitive

specs/DotNetProjectFile.Analyzers.Specs/Rules/MS_Build/Run_NuGet_security_audits_automatically.cs, src/DotNetProjectFile.Analyzers/Analyzers/MsBuild/RunNuGetSecurityAuditsAutomatically.cs, src/DotNetProjectFile.Analyzers/DotNetProjectFile.Analyzers.csproj, src/DotNetProjectFile.Analyzers/MsBuild/MsBuildDefaults.cs
From now on, only report when the feature is explicitly disabled.
See #93
=> Adjust Proj0004 to solve issue of NugetAudit being broken for the .NET 7 SDK

dotnet-project-file-analyzers.sln, projects/WithDirectoryBuildProps/Directory.Build.props, projects/WithDirectoryBuildProps/Placeholder.cs, projects/WithDirectoryBuildProps/WithDirectoryBuildProps.csproj, specs/DotNetProjectFile.Analyzers.Specs/MS_Build/Directory_Build_props_specs.cs, specs/DotNetProjectFile.Analyzers.Specs/Rules/MS_Build/Add_additional_files.cs, src/DotNetProjectFile.Analyzers/Analyzers/MsBuild/GuardUnsupported.cs, src/DotNetProjectFile.Analyzers/Diagnostics/ProjectFileAnalysisContext.cs, src/DotNetProjectFile.Analyzers/DotNetProjectFile.Analyzers.csproj, src/DotNetProjectFile.Analyzers/Extensions/Microsoft.CodeAnalysis.Diagnostics.AnalysisContext.cs, src/DotNetProjectFile.Analyzers/Extensions/System.IO.FileSystemInfo.cs, src/DotNetProjectFile.Analyzers/MsBuild/Project.cs, src/DotNetProjectFile.Analyzers/MsBuild/Projects.cs
A build can be [customized by directory](https://learn.microsoft.com/en-us/visualstudio/msbuild/customize-by-directory). Those `Directory.Build.props` should be validated by themselves, and have impact on validation project files too, as they can serve as the first ancestor in the inheritance chain.
=> Support Directory.Build.props

.github/workflows/build-test.yaml, projects/EmptyProjectVB/Placeholder.vb, projects/PropertiesTwice/PropertiesTwice.csproj, projects/ResxNoXml/ResxNoXml.csproj, projects/SonarVB/Placeholder.vb, props/common.props, specs/Benchmarks/Benchmarks.csproj, specs/DotNetProjectFile.Analyzers.Specs/DotNetProjectFile.Analyzers.Specs.csproj, specs/DotNetProjectFile.Analyzers.Specs/Rules/RESX/Embed_valid_resource_files.cs, src/DotNetProjectFile.Analyzers/DotNetProjectFile.Analyzers.csproj
.NET 7.0 is about to be out of support. Also we like to benefit from the newest Roslyn Test Tools that uses the newest version of [Buildalizer](https://github.com/daveaglick/Buildalyzer).
=> Update to .NET 8.0 with newest Roslyn Test Tools

specs/DotNetProjectFile.Analyzers.Specs/Rules/MS_Build/Add_additional_files.cs, src/DotNetProjectFile.Analyzers/Analyzers/MsBuild/AddAdditionalFile.cs, src/DotNetProjectFile.Analyzers/DotNetProjectFile.Analyzers.csproj
It is far from trivial to include the directory build props. Furthermore, it might be even available in all scenario's. #41
=> FP Proj0006: Directory.Build.Props is not required to be added as additional file

build.sln, dotnet-project-file-analyzers.sln, projects/CompliantCSharp/CompliantCSharp.csproj, projects/CompliantCSharpPackage/CompliantCSharpPackage.csproj, projects/DisableNetAnalyzers/DisableNetAnalyzers.csproj, projects/NoEnableNetAnalyzers/NoEnableNetAnalyzers.csproj, props/common.props, specs/DotNetProjectFile.Analyzers.Specs/Rules/MS_Build/Use_NET_analyzers.cs, src/DotNetProjectFile.Analyzers/Analyzers/MsBuild/UseDotNetAnalyzers.cs, src/DotNetProjectFile.Analyzers/DotNetProjectFile.Analyzers.csproj, src/DotNetProjectFile.Analyzers/Extensions/DotNetProjectFile.MsBuild.Project.cs, src/DotNetProjectFile.Analyzers/IO/FileSystemSelector.cs, src/DotNetProjectFile.Analyzers/MsBuild/EnableNETAnalyzers.cs, src/DotNetProjectFile.Analyzers/MsBuild/MsBuildDefaults.cs, src/DotNetProjectFile.Analyzers/MsBuild/Project.cs, src/DotNetProjectFile.Analyzers/MsBuild/PropertyGroup.cs, src/DotNetProjectFile.Analyzers/README.md, src/DotNetProjectFile.Analyzers/Rule.cs
Enable .NET analyzers by setting `<EnableNETAnalyzers>` to `true`.
See: #27.
=> New Rule 1002: Use Microsoft's analyzers

projects/UnstablePackageReferences/UnstablePackageReferences.csproj, specs/DotNetProjectFile.Analyzers.Specs/Rules/MS_Build/Package_references_should_be_stable.cs, src/DotNetProjectFile.Analyzers/Analyzers/MsBuild/PackageReferencesShouldBeStable.cs, src/DotNetProjectFile.Analyzers/DotNetProjectFile.Analyzers.csproj, src/DotNetProjectFile.Analyzers/README.md, src/DotNetProjectFile.Analyzers/Rule.cs
he use of nightly builds and other pre-releases should be avoided.
=> Proj1101: Package references should have stable versions

dictionary.dic, projects/FaultyIndenting/FaultyIndenting.csproj, projects/FaultyIndenting/FaultyIndenting.resx, specs/DotNetProjectFile.Analyzers.Specs/DotNetProjectFile.Analyzers.Specs.csproj, specs/DotNetProjectFile.Analyzers.Specs/Rules/MS_Build/Indent_XML.cs, specs/DotNetProjectFile.Analyzers.Specs/Rules/RESX/Indent_RESX.cs, src/DotNetProjectFile.Analyzers/Analyzers/Helpers/IdentationChecker.cs, src/DotNetProjectFile.Analyzers/Analyzers/MsBuild/IndentXml.cs, src/DotNetProjectFile.Analyzers/Analyzers/Resx/IndentResx.cs, src/DotNetProjectFile.Analyzers/CodeAnalysis/Locatable.cs, src/DotNetProjectFile.Analyzers/CodeAnalysis/Locations.cs, src/DotNetProjectFile.Analyzers/Diagnostics/DiagnosticReporter.cs, src/DotNetProjectFile.Analyzers/Diagnostics/ProjectFileAnalysisContext.cs, src/DotNetProjectFile.Analyzers/Diagnostics/ResourceFileAnalysisContext.cs, src/DotNetProjectFile.Analyzers/DotNetProjectFile.Analyzers.csproj, src/DotNetProjectFile.Analyzers/MsBuild/Node.cs, src/DotNetProjectFile.Analyzers/README.md, src/DotNetProjectFile.Analyzers/Resx/Node.cs, src/DotNetProjectFile.Analyzers/Resx/Resource.cs, src/DotNetProjectFile.Analyzers/Rule.cs, src/DotNetProjectFile.Analyzers/Xml/XmlAnalysisNode.cs
Simalar to #135 , also RESX files should be properly indented.
The reason that this is a separate rule is both that it can be turned on/of independently, but also because project files and RESX files have a different analyzer context.
=> Proj2100: Indent RESX

specs/DotNetProjectFile.Analyzers.Specs/Rules/MS_Build/Package_references_should_be_stable.cs, src/DotNetProjectFile.Analyzers/MsBuild/Project.cs
=> Include `Directory.Packages.props` when regestering actions

projects/MisuseVersionOverride/MisuseVersionOverride.csproj, projects/UseCPM/Directory.Packages.props, specs/DotNetProjectFile.Analyzers.Specs/Rules/MS_Build/Use_VersionOverride_only_with_CPM.cs, src/DotNetProjectFile.Analyzers/Analyzers/MsBuild/UseVersionOverrideOnlyWithCpm.cs, src/DotNetProjectFile.Analyzers/DotNetProjectFile.Analyzers.csproj, src/DotNetProjectFile.Analyzers/README.md, src/DotNetProjectFile.Analyzers/Rule.cs
When CPM is not enabled the use of `<PackageReference VersionOveride />` is pointless, and most likely a mistake.
See #130
=> Proj0803: Only use VersionOverride when CPM is enabled

projects/PackageReferenceWithoutVersion/Directory.Packages.props, projects/PackageReferenceWithoutVersion/PackageReferenceWithoutVersion.csproj, projects/PackageReferenceWithoutVersion/common.props, specs/DotNetProjectFile.Analyzers.Specs/Rules/MS_Build/CPM/Define_package_reference_version.cs, src/DotNetProjectFile.Analyzers/Analyzers/MsBuild/BuildActionIncludeShouldExist.cs, src/DotNetProjectFile.Analyzers/Analyzers/MsBuild/DefinePackageReferenceVersion.cs, src/DotNetProjectFile.Analyzers/DotNetProjectFile.Analyzers.csproj, src/DotNetProjectFile.Analyzers/MsBuild/Projects.cs
It turns out that the `Directory.Build.props` and `Directory.Packages.props` where not linked to `*.props` when they should. Another issue with this rule is due to the fact that MSB4018 fails with a crash. It seems that `Proj0805` therefor is not hit, and does not give the info we need. :(
Closes #159
=> Proj0805: could not resolve package versions in props file

projects/XmlDeclaration/XmlDeclaration.csproj, specs/DotNetProjectFile.Analyzers.Specs/Rules/MS_Build/Ommit_XML_declaration.cs, src/DotNetProjectFile.Analyzers/Analyzers/MsBuild/OmitXmlDeclarations.cs, src/DotNetProjectFile.Analyzers/DotNetProjectFile.Analyzers.csproj, src/DotNetProjectFile.Analyzers/MsBuild/Project.cs, src/DotNetProjectFile.Analyzers/README.md, src/DotNetProjectFile.Analyzers/Rule.cs
The XML declaration is redundant for MS Build project files.
=> Proj1702: Omit XML declarations

projects/BloatedDirectoryPackagesProps/Directory.Packages.props, projects/EnableCPMLocally/Directory.Packages.props, projects/MisuseVersion/Directory.Packages.props, projects/TargetFrameworksSingleWithBase/common.props, projects/UnstableVersionsCPM/Directory.Packages.props, projects/UseCPM/Directory.Packages.props, projects/VersionUpdateNotDifferent/Directory.Packages.props, projects/props/DoublePackageReferences.props, projects/props/common.props, projects/props/common1.props, projects/props/common2.props, projects/props/simple.props, props/common.props, specs/DotNetProjectFile.Analyzers.Specs/Rules/MS_Build/CPM/Use_Directory_Packages_props_only_for_CPM.cs, specs/DotNetProjectFile.Analyzers.Specs/Rules/MS_Build/Include_package_references_once.cs, specs/DotNetProjectFile.Analyzers.Specs/Rules/MS_Build/Reassign_properties_with_different_value.cs
Just apply [Proj1702](https://dotnet-project-file-analyzers.github.io/rules/Proj1702.html) to are test examples as much as possible.
=> Remove XML declarations from test props files

src/DotNetProjectFile.Analyzers/DotNetProjectFile.Analyzers.csproj, src/DotNetProjectFile.Analyzers/NuGet/Packages.cs
It's an SDK dependency that does only adjust the build targets.
=> Proj1200: Microsoft.NET.Test.Sdk should be considered a private asset

props/common.props, specs/DotNetProjectFile.Analyzers.Specs/DotNetProjectFile.Analyzers.Specs.csproj, src/DotNetProjectFile.Analyzers/DotNetProjectFile.Analyzers.csproj
It is a nice way to test our rules on our own test project. We have a unit test that already checks are main project, but that mechanism does not (yet) support projects with a project reference.
Note that we cannot - with this mechanism - add our analyzers to the project defining them.
=> Enable own analyzer for specs project

projects/TestProjectWithoutSdk/TestProjectWithoutSdk.csproj, projects/TestSdkOnly/TestSdkOnly.csproj, specs/DotNetProjectFile.Analyzers.Specs/DotNetProjectFile.Analyzers.Specs.csproj, specs/DotNetProjectFile.Analyzers.Specs/Rules/MS_Build/Test projects/Require_SDK.cs, specs/DotNetProjectFile.Analyzers.Specs/Rules/MS_Build/Test projects/Should_not_be_packable.cs, specs/DotNetProjectFile.Analyzers.Specs/Rules/MS_Build/Test projects/Should_not_be_publishable.cs, src/DotNetProjectFile.Analyzers/Analyzers/MsBuild/TestProjectsRequireSdk.cs, src/DotNetProjectFile.Analyzers/DotNetProjectFile.Analyzers.csproj, src/DotNetProjectFile.Analyzers/NuGet/Packages.cs, src/DotNetProjectFile.Analyzers/README.md, src/DotNetProjectFile.Analyzers/Rule.cs
If 'Microsoft.NET.Test.Sdk' is included, `<IsTestProject>` should be true, and vice versa.
=> Proj0452 & Proj0453: Microsoft.NET.Test.Sdk and IsTestProject should tell the same story

dictionary.dic, specs/DotNetProjectFile.Analyzers.Specs/Rules/RESX/Indent_RESX.cs, src/DotNetProjectFile.Analyzers/Analyzers/MsBuild/AvoidUsingMoq.cs, src/DotNetProjectFile.Analyzers/Analyzers/MsBuild/ExcludePrivateAssetDependencies.cs, src/DotNetProjectFile.Analyzers/Analyzers/MsBuild/PackageReferencesShouldBeStable.cs, src/DotNetProjectFile.Analyzers/Analyzers/MsBuild/UseSonarAnalyzers.cs, src/DotNetProjectFile.Analyzers/Extensions/System.String.cs, src/DotNetProjectFile.Analyzers/MsBuild/Project.cs, src/DotNetProjectFile.Analyzers/MsBuild/Projects.cs, src/DotNetProjectFile.Analyzers/NuGet/Analyzer.cs, src/DotNetProjectFile.Analyzers/Resx/Resources.cs, src/DotNetProjectFile.Analyzers/Rule.cs
To shorten the tons of places where `string.Equals(l, r, StringComparison.OrdinalIgnoreCase)` where applied.
=> Introduction of case-insensitive string.IsMatch(string?)

projects/FaultyIndenting/FaultyIndenting.resx, src/DotNetProjectFile.Analyzers/Analyzers/Helpers/IdentationChecker.cs, src/DotNetProjectFile.Analyzers/DotNetProjectFile.Analyzers.csproj, src/DotNetProjectFile.Analyzers/Extensions/System.Xml.Linq.XElement.cs, src/DotNetProjectFile.Analyzers/MsBuild/Node.cs, src/DotNetProjectFile.Analyzers/Resx/Node.cs, src/DotNetProjectFile.Analyzers/Xml/XmlAnalysisNode.cs
If we take a look at the following XML/RESX:
``` XML
<?xml version="1.0" encoding="utf-8"?>
<data name="Preserved" xml:space="preserve">
<value>Hello, world!
We should preserve what we've got.</value>
</data>
</root>
```
There should not be a report on the closing `</value>`. The ` xml:space="preserve"` gives meaning to the (lack of) spacing. This should be fixed now.
=> FP Proj2100: Space preserved closing nodes should not be reported

src/DotNetProjectFile.Analyzers/DotNetProjectFile.Analyzers.csproj, src/DotNetProjectFile.Analyzers/Rule.cs
Rule [Proj1100: Avoid using Moq](https://dotnet-project-file-analyzers.github.io/rules/Proj1100.html) states that Moq is doing things considered strongly immoral and potentially illegal and hence should not be used.
As this is not longer the case, should we disable the rule by default.
=> Disable Proj1100:  Avoid using Moq

specs/Benchmarks/README.md, src/DotNetProjectFile.Analyzers/Analyzers/MsBuild/OrderPackageReferencesAlphabetically.cs, src/DotNetProjectFile.Analyzers/Analyzers/MsBuild/OrderPackageVersionsAlphabetically.cs, src/DotNetProjectFile.Analyzers/Analyzers/MsBuild/OrderProjectReferencesAlphabetically.cs, src/DotNetProjectFile.Analyzers/Analyzers/MsBuild/OrderUsingDirectivesAlphabetically.cs, src/DotNetProjectFile.Analyzers/Analyzers/MsBuild/OrderUsingDirectivesByType.cs, src/DotNetProjectFile.Analyzers/Analyzers/MsBuild/StaticAliasUsingNotSupported.cs, src/DotNetProjectFile.Analyzers/DotNetProjectFile.Analyzers.csproj
As described in issue #194, some analyzers will crash (or misreport issues) on rules that also try to report on imports. This PR contains all straightforward adjustments.
=> Rules should only report on nodes defined in MS Build project file of current context

specs/Benchmarks/IniFile.cs, specs/Benchmarks/README.md, specs/DotNetProjectFile.Analyzers.Specs/Parsing/INI_syntax.cs, src/DotNetProjectFile.Analyzers/Collections/Slice.cs, src/DotNetProjectFile.Analyzers/Collections/SliceSpan.cs, src/DotNetProjectFile.Analyzers/Ini/HeaderSyntax.cs, src/DotNetProjectFile.Analyzers/Ini/IniFileSyntax.cs, src/DotNetProjectFile.Analyzers/Ini/KeySyntax.cs, src/DotNetProjectFile.Analyzers/Ini/KeyValuePairSyntax.cs, src/DotNetProjectFile.Analyzers/Ini/SectionSyntax.cs, src/DotNetProjectFile.Analyzers/Ini/ValueSyntax.cs, src/DotNetProjectFile.Analyzers/Ini/_grammar.cs, src/DotNetProjectFile.Analyzers/MsBuild/Project.Property.cs, src/DotNetProjectFile.Analyzers/Parsing/ParseBuffer.cs, src/DotNetProjectFile.Analyzers/Parsing/Parser.cs, src/DotNetProjectFile.Analyzers/Syntax/RootSyntax.cs, src/DotNetProjectFile.Analyzers/Syntax/SyntaxNode.cs, src/DotNetProjectFile.Analyzers/Syntax/SyntaxNodeCollection.cs, src/DotNetProjectFile.Analyzers/Syntax/SyntaxNodeResolver.cs, src/DotNetProjectFile.Analyzers/Syntax/SyntaxTree.cs
Support unparsable tokens to always parse the full INI file, even if some lines can not be parsed. Also improved on how to create the syntax tree.
=> Improve on INI grammar

specs/Benchmarks/Program.cs, specs/Benchmarks/README.md, src/DotNetProjectFile.Analyzers/Ini/_grammar.cs, src/DotNetProjectFile.Analyzers/Syntax/SourceSpan.cs
Microsoft's `SourceText` has (lazy created) fixed collection of lines. Specially for bigger files, this reduces the parsing times. It also reduces the amount of code needed. Hence, an improvement I'd like to keep.
|     File |         Old |         New |
|---------:|------------:|------------:|
|   27 LoC |    49.71 us |    41.41 us |
|   36 LoC |    54.55 us |    44.52 us |
| 1220 LoC | 7,819.40 us | 4,828.15 us |
=> Use source text's lines for parsing

projects/ResxWithHtmlContent/Messages.resx, projects/ResxWithHtmlContent/ResxWithHtmlContent.csproj, specs/DotNetProjectFile.Analyzers.Specs/Rules/RESX/Escape_XML_nodes_resource_values.cs, src/DotNetProjectFile.Analyzers/Analyzers/Resx/EscapeXmlNodesResourceValues.cs, src/DotNetProjectFile.Analyzers/DotNetProjectFile.Analyzers.csproj, src/DotNetProjectFile.Analyzers/README.md, src/DotNetProjectFile.Analyzers/Rule.cs
To ensure correct handling, XML nodes within resource values should be escaped.
Closes #215 
Documentation PR: https://github.com/dotnet-project-file-analyzers/dotnet-project-file-analyzers.github.io/pull/42
=> XML nodes within resource values should be escaped

src/DotNetProjectFile.Analyzers/DotNetProjectFile.Analyzers.csproj
Rule [RS1038](https://github.com/dotnet/roslyn-analyzers/blob/main/docs/rules/RS1038.md) states that `Microsoft.CodeAnalysis.Workspaces.Common` should not be referenced, but `Microsoft.CodeAnalysis.Common` instead. So, that is what I did.
Note that I only solved this issue for the analyzer assembly. The unit test assembly reports on this too, but I'd like to fix those issues in another PR.
=> Fix RS1038 warning

dictionary.dic, projects/CSharpOnlyProperties/CSharpOnlyProperties.csproj, projects/CSharpOnlyProperties/Directory.Build.props, projects/CSharpOnlyPropertiesVB/CSharpOnlyPropertiesVB.vbproj, projects/CSharpOnlyPropertiesVB/Directory.Build.props, specs/DotNetProjectFile.Analyzers.Specs/Rules/MS_Build/Use_CSharp_specific_only_in_CSharp_context.cs, specs/DotNetProjectFile.Analyzers.Specs/Rules/MS_Build/Use_VB_specific_only_in_VB_context.cs, src/DotNetProjectFile.Analyzers/Analyzers/MsBuild/UseInCSharpContextOnly.cs, src/DotNetProjectFile.Analyzers/Analyzers/MsBuild/UseInVBContextOnly.cs, src/DotNetProjectFile.Analyzers/DotNetProjectFile.Analyzers.csproj, src/DotNetProjectFile.Analyzers/MsBuild/CSharp/AllowUnsafeBlocks.cs, src/DotNetProjectFile.Analyzers/MsBuild/CSharp/CheckForOverflowUnderflow.cs, src/DotNetProjectFile.Analyzers/MsBuild/CSharp/Nullable.cs, src/DotNetProjectFile.Analyzers/README.md, src/DotNetProjectFile.Analyzers/Rule.cs
Equivalent to #223, but for C#. Currently, only 3 properties are involved.
=> Proj0029: Use C# specific properties only when applicable

dictionary.dic, projects/CaseInsensitive/CaseInsensitive.csproj, projects/CaseInsensitive/Extra.cs, specs/DotNetProjectFile.Analyzers.Specs/Rules/MS_Build/Adopt_preferred_casing.cs, src/DotNetProjectFile.Analyzers/Analyzers/MsBuild/AdoptPreferredCasing.cs, src/DotNetProjectFile.Analyzers/DotNetProjectFile.Analyzers.csproj, src/DotNetProjectFile.Analyzers/Extensions/System.Xml.Linq.XElement.cs, src/DotNetProjectFile.Analyzers/MsBuild/Node.cs, src/DotNetProjectFile.Analyzers/MsBuild/NodeFactory.cs, src/DotNetProjectFile.Analyzers/README.md, src/DotNetProjectFile.Analyzers/Rule.cs
After some consideration, I think it is better to first release a rule just checking for consistent casing, instead of also checking for potential spelling issues (#221). This should not (hardly) lead to any FP's, where the other might bring more harm then good (hopefully not).
=> Proj0031: Adopt preferred casing of nodes

src/DotNetProjectFile.Analyzers/CodeAnalysis/ProjectFiles.cs
This reduces both the scans on disk required, and mitigates in cases where the assemblies are not deployed in a sub directory of the project file.
=> Resolve project file from additional files if possible

src/DotNetProjectFile.Analyzers/DotNetProjectFile.Analyzers.csproj, src/DotNetProjectFile.Analyzers/NuGet/Packages.cs
Both `DotNetProjectFile.Analyzers.Sdk` as `Qowaiv.Diagnostics.Contracts` should be added as private assets too.
=> Add packages to be included as private assets

projects/IniSyntaxErrors/failing.ini, src/DotNetProjectFile.Analyzers.Sdk/DotNetProjectFile.Analyzers.Sdk.csproj, src/DotNetProjectFile.Analyzers.Sdk/DotNetProjectFile.Analyzers.Sdk.props, src/DotNetProjectFile.Analyzers/DotNetProjectFile.Analyzers.csproj, src/DotNetProjectFile.Analyzers/Rule.Ini.cs
In some scenario's parsing INI files (still) crashes. This leads to `AD0001` errors, what is unacceptable from a user scenario. Therefor, for now, disable them by default. 
Closes #254
=> Disable INI based rules by default

src/DotNetProjectFile.Analyzers.Sdk/DotNetProjectFile.Analyzers.Sdk.csproj, src/DotNetProjectFile.Analyzers.Sdk/DotNetProjectFile.Analyzers.Sdk.props
This happened because 
``` XML
<Project xmlns="http://schemas.microsoft.com/developer/msbuild/2003">
<ItemGroup>
<PackageReference Include="DotNetProjectFile.Analyzers" Version="1.5.3" PrivateAssets="all" />
</ItemGroup>
</Project>
```
always adds the `DotNetProjectFile.Analyzers` (as it should). Be removing it first, this should not longer occur.
=> Prevent NU1504 from being raised when Directory.Packages.props is used

projects/TargetFrameworkOverridesConditional/TargetFrameworkOverridesConditional.csproj, specs/DotNetProjectFile.Analyzers.Specs/Rules/MS_Build/Override_TargetFrameworks_with_TargetFrameworks.cs, src/DotNetProjectFile.Analyzers/Analyzers/MsBuild/OverrideTargetFrameworksWithTargetFrameworks.cs, src/DotNetProjectFile.Analyzers/DotNetProjectFile.Analyzers.csproj
If the `<TargetFrameworks>` has a different conditional constraint (not being none/null) using it beside `<TargetFramework>` is fine.
Closes #258
=> Proj0009: Take conditionals into account

specs/DotNetProjectFile.Analyzers.Specs/DotNetProjectFile.Analyzers.Specs.csproj, src/DotNetProjectFile.Analyzers.Sdk/DotNetProjectFile.Analyzers.Sdk.csproj, src/DotNetProjectFile.Analyzers/Analyzers/Helpers/IdentationChecker.cs, src/DotNetProjectFile.Analyzers/Analyzers/MsBuild/IndentXml.cs, src/DotNetProjectFile.Analyzers/Analyzers/Resx/IndentResx.cs, src/DotNetProjectFile.Analyzers/DotNetProjectFile.Analyzers.csproj, src/DotNetProjectFile.Analyzers/Rule.cs
Additional logic is past through the constructor, instead of the `Walk` method.
=> Move argument of IdentationChecker

projects/ToDo/Resources.resx, projects/ToDo/ToDo.csproj, specs/DotNetProjectFile.Analyzers.Specs/Rules/MS_Build/Track_TODO_tags.cs, src/DotNetProjectFile.Analyzers/Analyzers/Resx/TrackToDoTags.cs, src/DotNetProjectFile.Analyzers/DotNetProjectFile.Analyzers.csproj, src/DotNetProjectFile.Analyzers/README.md, src/DotNetProjectFile.Analyzers/Resx/Comment.cs, src/DotNetProjectFile.Analyzers/Resx/Node.Create.cs, src/DotNetProjectFile.Analyzers/Rule.cs
After implementing it for MS BUILD (#262), also implement it for RESX files. Part of this is updating the diagnostics ID from 0033 (MS BUILD range) to 3001 (Generic range).
See #250
=> Implement Track TODO tags for RESX

specs/DotNetProjectFile.Analyzers.Specs/Rules/MS_Build/Include_package_references_once.cs, specs/DotNetProjectFile.Analyzers.Specs/Rules/MS_Build/Track_TODO_tags.cs, src/DotNetProjectFile.Analyzers.Sdk/DotNetProjectFile.Analyzers.Sdk.csproj, src/DotNetProjectFile.Analyzers/Analyzers/EditorConfig/HeaderMustBeGlob.cs, src/DotNetProjectFile.Analyzers/Analyzers/EditorConfig/UseEqualsAssign.cs, src/DotNetProjectFile.Analyzers/Analyzers/Helpers/IdentationChecker.cs, src/DotNetProjectFile.Analyzers/Analyzers/Helpers/ToDoChecker.cs, src/DotNetProjectFile.Analyzers/Analyzers/Ini/EmptySection.cs, src/DotNetProjectFile.Analyzers/Analyzers/MsBuild/ConfigureCentralPackageVersionManagement.cs, src/DotNetProjectFile.Analyzers/Analyzers/MsBuild/IncludeDirectoryPackagesProps.cs, src/DotNetProjectFile.Analyzers/Analyzers/MsBuild/OmitXmlDeclarations.cs, src/DotNetProjectFile.Analyzers/Analyzers/MsBuild/UseCDATAForLargeTexts.cs, src/DotNetProjectFile.Analyzers/Diagnostics/ProjectFileAnalysisContext.cs, src/DotNetProjectFile.Analyzers/DotNetProjectFile.Analyzers.csproj, src/DotNetProjectFile.Analyzers/MsBuild/Node.cs, src/DotNetProjectFile.Analyzers/Resx/Node.cs, src/DotNetProjectFile.Analyzers/Xml/XmlAnalysisNode.cs, src/DotNetProjectFile.Analyzers/Xml/XmlComment.cs
Closes #266 
It turned out that in many cases we assumed that the `.ReportDiagnostic` was called on the context of the file we were reporting an error in, which didn't always turn out to be a correct assumption.
I solved this by:
- hoisting the `ProjectFile` `Project` property to the `XmlAnalysisNode` interface.
- Updating `XmlAnalysisNode` implementations to match the new interface.
- Use the `ProjectFile` from the `XmlAnalysisNode` we are reporting on, rather than the one from the context.
- Added a mandatory `ProjectFile` argument to the `.ReportDiagnostic` method that takes a linespan, in order to prevent accidental incorrect usage.
=> Fix error reporting in wrong files

specs/DotNetProjectFile.Analyzers.Specs/Rules/MS_Build/CPM/Configure_CPM.cs, specs/DotNetProjectFile.Analyzers.Specs/Rules/MS_Build/CPM/Include_Directory_Packages_props.cs, specs/DotNetProjectFile.Analyzers.Specs/Rules/MS_Build/Ommit_XML_declaration.cs, specs/DotNetProjectFile.Analyzers.Specs/Rules/MS_Build/Use_CDATA_for_large_texts.cs, src/DotNetProjectFile.Analyzers/Analyzers/Helpers/IdentationChecker.cs, src/DotNetProjectFile.Analyzers/Analyzers/Helpers/ToDoChecker.cs, src/DotNetProjectFile.Analyzers/Analyzers/MsBuild/ConfigureCentralPackageVersionManagement.cs, src/DotNetProjectFile.Analyzers/Analyzers/MsBuild/GuardUnsupported.cs, src/DotNetProjectFile.Analyzers/Analyzers/MsBuild/IncludeDirectoryPackagesProps.cs, src/DotNetProjectFile.Analyzers/Analyzers/MsBuild/OmitXmlDeclarations.cs, src/DotNetProjectFile.Analyzers/Analyzers/MsBuild/UseCDATAForLargeTexts.cs, src/DotNetProjectFile.Analyzers/Diagnostics/ProjectFileAnalysisContext.cs, src/DotNetProjectFile.Analyzers/DotNetProjectFile.Analyzers.csproj, src/DotNetProjectFile.Analyzers/MsBuild/Node.cs, src/DotNetProjectFile.Analyzers/Resx/Node.cs, src/DotNetProjectFile.Analyzers/Xml/XmlAnalysisNode.cs, src/DotNetProjectFile.Analyzers/Xml/XmlComment.cs, src/DotNetProjectFile.Analyzers/Xml/XmlLocations.cs, src/DotNetProjectFile.Analyzers/Xml/XmlPositions.cs
`XmlLocations` is an object that combines the `XmlPositions` with the `ProjectFile`. It allows the `XmlPositions` to be created without having the knowledge of the `ProjectFile` and the reporting not to have to specify the `ProjectFile` being reported on.
Closes #269
=> Introduction of XML Locations

projects/TUnitTestProject/TUnitTestProject.csproj, specs/DotNetProjectFile.Analyzers.Specs/Rules/MS_Build/Test projects/Require_SDK.cs, src/DotNetProjectFile.Analyzers/Analyzers/MsBuild/TestProjectsRequireSdk.cs, src/DotNetProjectFile.Analyzers/DotNetProjectFile.Analyzers.csproj, src/DotNetProjectFile.Analyzers/NuGet/Packages.cs
- TUnit.Analyzer and TUnit.Assertions.Analyzer are deprecated, so they shouldn't be recommended anymore (the analyzers are now included in the main packages).
- TUnit doesn't use VSTest and therefore doesn't require the test SDK (it even breaks if the test SDK is loaded).
=> Fix TUnit related false positives

specs/DotNetProjectFile.Analyzers.Specs/Extensions/Microsoft.CodeAnalysis.Diagnostics.DiagnosticAnalyzer.cs, specs/DotNetProjectFile.Analyzers.Specs/Properties/AssemblyInfo.cs, specs/DotNetProjectFile.Analyzers.Specs/Rules/Generic/Only_use_UTF-8_without_BOM.cs, specs/DotNetProjectFile.Analyzers.Specs/TestTools/CachedProjectLoader.cs
Caches loaded projects to speed up the tests. This reduced the time to run all tests on the machine where I wrote the changes by roughly 60% (10 min -> 4 min). Perhaps this change should be moved to your roslyn test tools package, but for now this was some low hanging fruit for this project, since this doesn't properly deal with the scenario where the cache gets too crowded and runs into potential memory issues.
Edit: also made the tests run in parallel, which reduced the time further to only 1 minute (for a total of 90% reduction in execution time).
Edit 2: this also makes the pipeline run in 2.5 minutes instead of 8.5 minutes.
=> Cache test projects & Execute in parallel

README.md, specs/DotNetProjectFile.Analyzers.Specs/Extensions/Microsoft.CodeAnalysis.Diagnostics.DiagnosticAnalyzer.cs, specs/DotNetProjectFile.Analyzers.Specs/Rules/MS_Build/Enable_api_compatibility_attribute_checks.cs, specs/DotNetProjectFile.Analyzers.Specs/Rules/MS_Build/Enable_api_compatibility_parameter_name_checks.cs, specs/DotNetProjectFile.Analyzers.Specs/Rules/MS_Build/Enable_strict_mode_for_package_baseline_validation.cs, specs/DotNetProjectFile.Analyzers.Specs/Rules/MS_Build/Enable_strict_mode_for_package_framework_validation.cs, specs/DotNetProjectFile.Analyzers.Specs/Rules/MS_Build/Enable_strict_mode_for_package_runtime_validation.cs, specs/DotNetProjectFile.Analyzers.Specs/Rules/MS_Build/Generate_api_compatibility_suppression_file.cs, src/DotNetProjectFile.Analyzers/Analyzers/MsBuild/EnableApiCompatibilityAttributeChecks.cs, src/DotNetProjectFile.Analyzers/Analyzers/MsBuild/EnableApiCompatibilityParameterNameChecks.cs, src/DotNetProjectFile.Analyzers/Analyzers/MsBuild/EnableStrictModeForPackageBaselineValidation.cs, src/DotNetProjectFile.Analyzers/Analyzers/MsBuild/EnableStrictModeForPackageFrameworkCompatibilityValidation.cs, src/DotNetProjectFile.Analyzers/Analyzers/MsBuild/EnableStrictModeForPackageRuntimeCompatibilityValidation.cs, src/DotNetProjectFile.Analyzers/Analyzers/MsBuild/GenerateApiCompatibilitySuppressionFile.cs, src/DotNetProjectFile.Analyzers/DotNetProjectFile.Analyzers.csproj, src/DotNetProjectFile.Analyzers/MsBuild/ApiCompatEnableRuleAttributesMustMatch.cs, src/DotNetProjectFile.Analyzers/MsBuild/ApiCompatEnableRuleCannotChangeParameterName.cs, src/DotNetProjectFile.Analyzers/MsBuild/ApiCompatGenerateSuppressionFile.cs, src/DotNetProjectFile.Analyzers/MsBuild/EnableStrictModeForBaselineValidation.cs, src/DotNetProjectFile.Analyzers/MsBuild/EnableStrictModeForCompatibleFrameworksInPackage.cs, src/DotNetProjectFile.Analyzers/MsBuild/EnableStrictModeForCompatibleTfms.cs, src/DotNetProjectFile.Analyzers/MsBuild/PropertyGroup.cs, src/DotNetProjectFile.Analyzers/README.md, src/DotNetProjectFile.Analyzers/Rule.cs
Implementations of https://github.com/dotnet-project-file-analyzers/dotnet-project-file-analyzers.github.io/pull/83
Also introduced a system to define in-line project files, since creating the physical files on disk is becoming quite tiresome to me (and I believe this also makes it easier to understand what a test case is verifying without having to open additional files).
=> More package validation rules

projects/CompliantCSharp/Messages.nl.resx, projects/CompliantCSharp/Messages.resx, projects/CompliantCSharpPackage/Messages.nl.resx, projects/CompliantCSharpPackage/Messages.resx, projects/ResxUnsorted/ResxUnsorted.csproj, src/DotNetProjectFile.Analyzers/CodeAnalysis/ProjectFiles.cs, src/DotNetProjectFile.Analyzers/DotNetProjectFile.Analyzers.csproj, src/DotNetProjectFile.Analyzers/Extensions/Microsoft.CodeAnalysis.Diagnostics.AnalysisContext.cs
I was under the impression for some time that embedded resources where added as additional files by default, and that the only reason our test tools did pick add them to the additional files was due to an issue with those tools (Buildalyzer). I apparently never tested this assumption correctly, or the behavior did change (way less likely).
Long story short, with this fix, all resource files that are not added as additional files are also analyzed.
=> Report on RESX files that are not added as additional files

README.md, projects/CompliantCSharp/CompliantCSharp.csproj, projects/CompliantCSharpPackage/CompliantCSharpPackage.csproj, specs/DotNetProjectFile.Analyzers.Specs/Rules/RESX/Add_additional_files.cs, src/DotNetProjectFile.Analyzers/Analyzers/Resx/AddAdditionalFile.cs, src/DotNetProjectFile.Analyzers/DotNetProjectFile.Analyzers.csproj
See #305 . So Proj0006 should be extended. This also means that the documentation should be extended. Not only that, but the rule now becomes a generic rule (applies both to RESX, and MS Build files), we could to introduce a new rule ID for it (and mark the old one as obsolete, of drop it).
=> Proj0006: Report on RESX files that are not added as additional files

.github/workflows/build-test.yaml
Closes #249 
Automatically push the `DotNetProjectFile.Analyzers` and `DotNetProjectFile.Analyzers.Sdk` packages in the pipeline. It is straight forward to push to nuget, but tagging the branch seems to require alot of custom steps. To tag the branch we:
- check if the push of `DotNetProjectFile.Analyzers` was successful (through the exit code),
- use the package name to extract the version Id,
- tag the branch.
So while the automatic tagging is nice, all the custom scripts could make it fragile. Potential other ways could be:
- Trigger the workflow instead when a `vx.x.x` tag is manually pushed.
- Remove the automatic tagging process and keep it a manual process, while the build & push pipeline still runs automatically.
Suggestions or preferences are welcome.
=> Publish packages in pipeline

specs/DotNetProjectFile.Analyzers.Specs/NuGet/Nuspec_file_specs.cs, specs/DotNetProjectFile.Analyzers.Specs/TestTools/Streams.cs, src/DotNetProjectFile.Analyzers/DotNetProjectFile.Analyzers.csproj, src/DotNetProjectFile.Analyzers/NuGet/Packaging/Metadata.cs, src/DotNetProjectFile.Analyzers/NuGet/Packaging/NuSpecFile.cs
To be able to analyze `.nuspec` files it is beneficial to have a well defined representation of its structure.
=> Implement the NuSpec file

projects/UnresolvableImport/UnresolvableImport.csproj, projects/UnresolvableImport/common.props, specs/DotNetProjectFile.Analyzers.Specs/Rules/MS_Build/Unresolvable_Import.cs, src/DotNetProjectFile.Analyzers/DotNetProjectFile.Analyzers.csproj, src/DotNetProjectFile.Analyzers/MsBuild/UnresolvableImport.cs, src/DotNetProjectFile.Analyzers/README.md, src/DotNetProjectFile.Analyzers/Rule.cs
As a result of #321, we should inform the use that we could not resolve the import, and do not perform analysis on rules that require the import statements to work (See #330 ).
=> Proj0034: Import statement could not be resolved

specs/DotNetProjectFile.Analyzers.Specs/NuGet/Nuspec_file_specs.cs, src/DotNetProjectFile.Analyzers/Analyzers/MsBuild/ExcludePrivateAssetDependencies.cs, src/DotNetProjectFile.Analyzers/Analyzers/MsBuild/GlobalPackageReferencesAreMeantForPrivateAssetsOnly.cs, src/DotNetProjectFile.Analyzers/Extensions/System.Linq.Enumerable.cs, src/DotNetProjectFile.Analyzers/NuGet/CachedPackage.cs, src/DotNetProjectFile.Analyzers/NuGet/PackageCache.cs, src/DotNetProjectFile.Analyzers/NuGet/PackageInfo.cs, src/DotNetProjectFile.Analyzers/NuGet/Packaging/Metadata.cs, src/DotNetProjectFile.Analyzers/NuGet/Packaging/MetadataLicense.cs, src/DotNetProjectFile.Analyzers/NuGet/Packaging/NuSpecFile.cs
Rule [Proj1200: Exclude private assets as project file dependency](https://dotnet-project-file-analyzers.github.io/rules/Proj1200.html) currently has a fixed set of packages we advise it for. With the cache in place, and also collecting the `<developmentDependency>` I think it would be better to start using that data to give advise when to markreferences as private assets.
=> Use cache for dependency types

src/DotNetProjectFile.Analyzers/Analyzers/MsBuild/GenerateSbom.cs, src/DotNetProjectFile.Analyzers/Analyzers/MsBuild/UseAnalyzersForPackages.cs, src/DotNetProjectFile.Analyzers/MsBuild/GlobalPackageReference.cs, src/DotNetProjectFile.Analyzers/MsBuild/PackageReference.cs, src/DotNetProjectFile.Analyzers/MsBuild/PackageReferenceBase.cs, src/DotNetProjectFile.Analyzers/MsBuild/PackageVersion.cs, src/DotNetProjectFile.Analyzers/NuGet/Analyzer.cs, src/DotNetProjectFile.Analyzers/NuGet/Package.cs
As `PackageReference`, `PackageVersion`, and `GlobalPackageReference` have a lot in common, it is beneficial to let them have a shared base class.
=> Introduction of PackageReferenceBase

specs/DotNetProjectFile.Analyzers.Specs/Rules/MS_Build/Thrid_Party_license_compliance.cs, src/DotNetProjectFile.Analyzers/Analyzers/MsBuild/ThirdPartyLicenseResolver.cs, src/DotNetProjectFile.Analyzers/Licensing/CustomLicense.cs, src/DotNetProjectFile.Analyzers/Licensing/Licenses.cs
To make a clear distinction between unknown and custom licenses (such as that of Sonar Source, or XCeed) I've created a custom license, containing an (SHA1) hash.
The idea is that custom licenses should be registered, to be allowed. Previously I've suggested to define this in a MS Build property, but an MS Build item might be more convenient:
``` XML
<ItemGroup Label="Custom licenses">
<CustomLicense Include="FluentAssertions" Hash="RQN3OPC/wYxT+eMudU1hVTy7smo" />
</ItemGroup>
```
=> Introduction of custom license

README.md, specs/DotNetProjectFile.Analyzers.Specs/Rules/MS_Build/ThirdPartyLicensence_compliance.cs, src/DotNetProjectFile.Analyzers/Analyzers/MsBuild/ThirdPartyLicenseCompliance.cs, src/DotNetProjectFile.Analyzers/Analyzers/MsBuild/ThirdPartyLicensenCompliance.cs, src/DotNetProjectFile.Analyzers/DotNetProjectFile.Analyzers.csproj, src/DotNetProjectFile.Analyzers/Licensing/CustomLicense.cs, src/DotNetProjectFile.Analyzers/MsBuild/ItemGroup.cs, src/DotNetProjectFile.Analyzers/README.md, src/DotNetProjectFile.Analyzers/Rule.cs
Closes #385 
It is not necessary to check if the `<ThirdPartyLicense>` is a child of `<ItemGroup>` or not. If you put it under a `<PropertyGroup>` you get a MSBuild error. So that rule (as suggested with #385) has not been implemented.
I went for three distinct rules, all as errors.
=> Rules to validate <ThirdPartyLicense>

src/DotNetProjectFile.Analyzers/Analyzers/MsBuild/RemoveCommentedOutCode.cs, src/DotNetProjectFile.Analyzers/Analyzers/Resx/RemoveCommentedOutCode.cs, src/DotNetProjectFile.Analyzers/DotNetProjectFile.Analyzers.csproj
I am bothered by the fact that searching for `dotnet project file analyzer` does not make the library appear on nuget, whereas it does appear when searching for `project file analyzer`. I hope adding `dotnet` as a tag will solve this.
=> Add dotnet as extra search tag

projects/PackagesWithoutAnalyzers/PackagesWithoutAnalyzers.csproj, specs/DotNetProjectFile.Analyzers.Specs/Rules/MS_Build/Use_analyzers_for_packages.cs, src/DotNetProjectFile.Analyzers/Analyzers/MsBuild/ExcludePrivateAssetDependencies.cs, src/DotNetProjectFile.Analyzers/Analyzers/MsBuild/GlobalPackageReferencesAreMeantForPrivateAssetsOnly.cs, src/DotNetProjectFile.Analyzers/Analyzers/MsBuild/ThirdPartyLicenseResolver.cs, src/DotNetProjectFile.Analyzers/Analyzers/MsBuild/UseAnalyzersForPackages.cs, src/DotNetProjectFile.Analyzers/DotNetProjectFile.Analyzers.csproj, src/DotNetProjectFile.Analyzers/MsBuild/PackageReference.cs, src/DotNetProjectFile.Analyzers/MsBuild/PackageReferenceBase.cs, src/DotNetProjectFile.Analyzers/NuGet/Analyzer.cs, src/DotNetProjectFile.Analyzers/NuGet/CachedPackage.cs, src/DotNetProjectFile.Analyzers/NuGet/PackageCache.cs, src/DotNetProjectFile.Analyzers/NuGet/Packages.cs
Closes #391
Also includes logic to resolve transitive dependencies from package references, which can be used for extending the license analyzers later on.
=> Change suggested analyzer logic to use packagereferences rather than assembly names

specs/DotNetProjectFile.Analyzers.Specs/Rules/MS_Build/Enable_api_compatibility_attribute_checks.cs, specs/DotNetProjectFile.Analyzers.Specs/Rules/MS_Build/Enable_api_compatibility_parameter_name_checks.cs, specs/DotNetProjectFile.Analyzers.Specs/Rules/MS_Build/Enable_strict_mode_for_package_baseline_validation.cs, specs/DotNetProjectFile.Analyzers.Specs/Rules/MS_Build/Enable_strict_mode_for_package_framework_validation.cs, specs/DotNetProjectFile.Analyzers.Specs/Rules/MS_Build/Generate_SBOM.cs, specs/DotNetProjectFile.Analyzers.Specs/Rules/MS_Build/Generate_api_compatibility_suppression_file.cs, specs/DotNetProjectFile.Analyzers.Specs/Rules/MS_Build/Generate_documentation_file.cs, specs/DotNetProjectFile.Analyzers.Specs/Rules/MS_Build/Test projects/Require_SDK.cs, specs/DotNetProjectFile.Analyzers.Specs/Rules/MS_Build/Test projects/Should_not_be_packable.cs, specs/DotNetProjectFile.Analyzers.Specs/Rules/MS_Build/Test projects/Should_not_be_publishable.cs, specs/DotNetProjectFile.Analyzers.Specs/Rules/MS_Build/Test projects/TUnit_usage.cs, src/DotNetProjectFile.Analyzers/Diagnostics/ProjectFileAnalysisContext.cs, src/DotNetProjectFile.Analyzers/DotNetProjectFile.Analyzers.csproj
With this change you'll only see issue wiggles for the start element, instead of the whole document when reporting on the root node. So:
``` XML
<Project>
^^^^^^^^^
<TargetFramework>net8.0</TargetFramework>
</Project>
```
Instead of
``` XML
<Project>
^^^^^^^^^
^^^^^^^^^^^^^^^^^
<TargetFramework>net8.0</TargetFramework>
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
^^^^^^^^^^^^^^^^^^
</Project>
^^^^^^^^^^
```
=> Report issues on root node only on start element

src/DotNetProjectFile.Analyzers/Analyzers/MsBuild/DefinePackageReferenceAssetsAsAttributes.cs, src/DotNetProjectFile.Analyzers/Analyzers/MsBuild/ExcludePrivateAssetDependencies.cs, src/DotNetProjectFile.Analyzers/Analyzers/MsBuild/GlobalPackageReferencesAreMeantForPrivateAssetsOnly.cs, src/DotNetProjectFile.Analyzers/Analyzers/MsBuild/RemoveUnusedPackageVersions.cs, src/DotNetProjectFile.Analyzers/Analyzers/MsBuild/ThirdPartyLicenseResolver.cs, src/DotNetProjectFile.Analyzers/DotNetProjectFile.Analyzers.csproj
=> Fix missing package names in warnings when reference is an update instead of include

globalconfig.verified.txt, projects/ProjectReferenceMissingInclude/ProjectReferenceMissingInclude.csproj, specs/Benchmarks/Benchmarks.csproj, specs/DotNetProjectFile.Analyzers.Specs/DotNetProjectFile.Analyzers.Specs.csproj, specs/DotNetProjectFile.Analyzers.Specs/Licensing/LicenseTexts/Manual/NET_Library_EULA_ENU/web_without_french.txt, specs/DotNetProjectFile.Analyzers.Specs/Rules/MS_Build/ThirdPartyLicensence_compliance.cs, specs/DotNetProjectFile.Analyzers.Specs/Rules/MS_Build/Treat_warnings_as_warnings.cs, src/DotNetProjectFile.Analyzers.Sdk/DotNetProjectFile.Analyzers.Sdk.csproj, src/DotNetProjectFile.Analyzers/Analyzers/MsBuild/TreatWarningsAsWarnings.cs, src/DotNetProjectFile.Analyzers/DotNetProjectFile.Analyzers.csproj, src/DotNetProjectFile.Analyzers/MsBuild/TreatWarningsAsErrors.cs, src/DotNetProjectFile.Analyzers/NuGet/PackageCache.cs, src/DotNetProjectFile.Analyzers/README.md, src/DotNetProjectFile.Analyzers/Rule.cs
Closes #405 
For documentation see: https://github.com/dotnet-project-file-analyzers/dotnet-project-file-analyzers.github.io/pull/109
=> Proj0039: Treat all warnings as errors is considered a bad practice

specs/DotNetProjectFile.Analyzers.Specs/Rules/MS_Build/Third_Party_license_compliance.cs, src/DotNetProjectFile.Analyzers.Sdk/DotNetProjectFile.Analyzers.Sdk.csproj, src/DotNetProjectFile.Analyzers/Analyzers/MsBuild/ThirdPartyLicenseResolver.cs, src/DotNetProjectFile.Analyzers/DotNetProjectFile.Analyzers.csproj, src/DotNetProjectFile.Analyzers/MsBuild/ThirdPartyLicense.cs, src/DotNetProjectFile.Analyzers/NuGet/PackageCache.cs
To check if there is a matching third-party license the code checked for the `<PackageReference>` info, which should match the reference, but logically *not* the transient dependency.
Closes #455
=> Verify third-party licenses on package info

specs/DotNetProjectFile.Analyzers.Specs/Rules/MS_Build/Enable_package_validation.cs, src/DotNetProjectFile.Analyzers/DotNetProjectFile.Analyzers.csproj, src/DotNetProjectFile.Analyzers/Rule.cs
Development dependencies most likely don't need to have a consistent API, so that would make more sense. The analyzer implementation already behaves like this, so it was most likely a typo or copy-paste error in the message text.
=> Fix Proj0240 message incorrectly suggesting to disable DevelopmentDependency, rather than to enable it

src/DotNetProjectFile.Analyzers/Analyzers/MsBuildProjectFileAnalyzer.cs, src/DotNetProjectFile.Analyzers/DotNetProjectFile.Analyzers.csproj
To be able to meta analysis on project files, all child project files (`*.csproj` and `*.vbproj`) are available as additional files, for the .net.csproj SDK.
This will trigger code to validate project files both via the build of that project file itself, as via the build of the .net.csproj SDK. The latter is undesirable, as is could potentially lead to rules evaluating incorrectly, and it also is done twice.
=> Analysis on project files are not longer executed for the SDK

specs/DotNetProjectFile.Analyzers.Specs/Rules/MS_Build/Global_package_references_are_meant_fo_private_assets_only.cs, specs/DotNetProjectFile.Analyzers.Specs/Rules/MS_Build/Remove_IncludeAssets_when_redundant.cs
I started #477 because I thought that
``` xml
<PackageReference Update="SonarAnalyzer.CSharp">
<PrivateAssets>all</PrivateAssets>
<IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
</PackageReference>
```
was not reported on. I was wrong. Nevertheless, I added the testcase.
=> Add testcase for assumed FP

docs/README.md, docs/navigation/editorconfig_rules.md, docs/navigation/ini_rules.md, docs/navigation/licensing.md, docs/navigation/slnx_rules.md, docs/rules/Proj5005.md, src/DotNetProjectFile.Analyzers/Analyzers/Slnx/OmitProjectIds.cs, src/DotNetProjectFile.Analyzers/DotNetProjectFile.Analyzers.csproj, src/DotNetProjectFile.Analyzers/README.md, src/DotNetProjectFile.Analyzers/Rule.SLNX.cs, src/DotNetProjectFile.Analyzers/Slnx/Project.cs, src/DotNetProjectFile.Analyzers/Slnx/Solution.cs
Closes #425 
Creating tests for SLNX files should be as simple as creating tests for CS-Project files. Because that is not the case I left the unit test out for now, and created an issue to solve that issue (separately).
=> Proj5005: Omit Project ID's
